export const images = {
  saladinImg: require('./source/Saladin.png'),
  insuranceImg: require('./source/insurance.png'),
  imgCar1: require('./source/Car1.png'),
  imgCar2: require('./source/Car2.png'),
  imgCar3: require('./source/Car3.png'),
  imgHotel1: require('./source/hotel1.png'),
  imgHotel2: require('./source/hotel2.png'),
  imgHotel3: require('./source/hotel3.png'),
  imgHotel4: require('./source/hotel4.png'),
  imgHotel5: require('./source/hotel5.png'),
  imgHotel6: require('./source/hotel6.png'),
  imgRoom1: require('./source/room1.png'),
  imgRoom2: require('./source/room2.png'),
  imgRoom3: require('./source/room3.png'),
  imgRoom4: require('./source/room4.png'),
  imgRoom5: require('./source/room5.png'),
  checkin_online: require('./source/checkin-online.png'),

  // Services
  IMG1: require('./source/services/IMG1.png'),
  IMG2: require('./source/services/IMG2.png'),
  IMG3: require('./source/services/IMG3.png'),
  IMG4: require('./source/services/IMG4.png'),
  IMG5: require('./source/services/IMG5.png'),
  IMG6: require('./source/services/IMG6.png'),
  IMG7: require('./source/services/IMG7.png'),
  IMG8: require('./source/services/IMG8.png'),
  IMG9: require('./source/services/IMG9.png'),
  IMG10: require('./source/services/IMG10.png'),
  IMG11: require('./source/services/IMG11.png'),
  IMG12: require('./source/services/IMG12.png'),
  IMG13: require('./source/services/IMG13.png'),
  IMG14: require('./source/services/IMG14.png'),
  IMG15: require('./source/services/IMG15.png'),
  IMG16: require('./source/services/IMG16.png'),
  IMG17: require('./source/services/IMG17.png'),
  IMG18: require('./source/services/IMG18.png'),
  IMG19: require('./source/services/IMG19.png'),
  IMG20: require('./source/services/IMG20.png'),
  IMG21: require('./source/services/IMG21.png'),
  IMG22: require('./source/services/IMG22.png'),
  IMG23: require('./source/services/IMG23.png'),
  IMG24: require('./source/services/IMG24.png'),
  IMG25: require('./source/services/IMG25.png'),
  IMG26: require('./source/services/IMG26.png'),
  IMG27: require('./source/services/IMG27.png'),
  IMG28: require('./source/services/IMG28.png'),
  IMG29: require('./source/services/IMG29.png'),
  IMG30: require('./source/services/IMG30.png'),
  IMG31: require('./source/services/IMG31.png'),
  IMG32: require('./source/services/IMG32.png'),
  IMG33: require('./source/services/IMG33.png'),
};

export type ImageTypes = keyof typeof images;
