import { Email } from '@services/axios';
import { ContentLst } from '@services/axios/axios-data';
import { Content } from '@services/axios/axios-email';
import { dbsContentActions } from '@vna-base/redux/action-slice';
import { delay, validResponse } from '@vna-base/utils';
import { takeLatestListeners } from '@vna-base/utils/redux/listener';
import { AxiosResponse } from 'axios';

export const runDBSContentListener = () => {
  takeLatestListeners()({
    actionCreator: dbsContentActions.getListSpecializeNews,
    effect: async (action, listenerApi) => {
      listenerApi.dispatch(dbsContentActions.changeLoadingSpecializeNews(true));

      const { pageIndex } = action.payload;

      // const response = await Email.contentHelperContentHelperGetListCreate({
      //   PageSize: PAGE_SIZE_DBS_CONTENT,
      //   PageIndex: pageIndex ?? 1,
      //   OrderBy: 'CreatedDate',
      //   SortType: SortType.Desc,
      //   Filter: [
      //     {
      //       Contain: false,
      //       Name: 'Highlight',
      //       Value: 'false',
      //     },
      //   ],
      //   GetAll: false,
      // });

      const response = await fakeGetListSpecializeNews();

      if (validResponse(response)) {
        listenerApi.dispatch(
          dbsContentActions.saveListSpecializeNews({
            List: response.data.List,
            PageIndex: response.data.PageIndex,
            TotalPage: response.data.TotalPage,
          }),
        );
      }

      listenerApi.dispatch(
        dbsContentActions.changeLoadingSpecializeNews(false),
      );
    },
  });

  takeLatestListeners()({
    actionCreator: dbsContentActions.getListOutStandingPolicy,
    effect: async (action, listenerApi) => {
      listenerApi.dispatch(dbsContentActions.changeLoadingPolicy(true));

      const { pageIndex } = action.payload;

      // const response = await Email.contentHelperContentHelperGetListCreate({
      //   PageSize: PAGE_SIZE_DBS_CONTENT,
      //   PageIndex: pageIndex ?? 1,
      //   OrderBy: 'CreatedDate',
      //   SortType: SortType.Desc,
      //   Filter: [
      //     {
      //       Contain: false,
      //       Name: 'Highlight',
      //       Value: 'true',
      //     },
      //   ],
      //   GetAll: false,
      // });

      const response = await fakeGetListOutStandingPolicy();

      if (validResponse(response)) {
        listenerApi.dispatch(
          dbsContentActions.saveListOutStandingPolicy({
            List: response.data.List,
            PageIndex: response.data.PageIndex,
            TotalPage: response.data.TotalPage,
          }),
        );
      }

      listenerApi.dispatch(dbsContentActions.changeLoadingPolicy(false));
    },
  });

  takeLatestListeners(true)({
    actionCreator: dbsContentActions.getDetailDBSContent,
    effect: async (actions, listenerApi) => {
      const { id } = actions.payload;
      const res = await Email.contentHelperContentHelperGetByIdCreate({
        Id: id,
      });

      if (validResponse(res)) {
        listenerApi.dispatch(
          dbsContentActions.saveDetailContent({
            [id]: res?.data?.Item as Content,
          }),
        );
      }
    },
  });
};

async function fakeGetListSpecializeNews(): Promise<
  AxiosResponse<ContentLst, any>
> {
  await delay(1000);

  return {
    data: {
      List: [
        {
          Id: 'F21C94F1-C87D-4A3E-9841-7CEF1DA1879E',
          Index: 332,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'EE626B9F-D336-4410-89A9-2C2E55307630',
          Language: 'vi',
          Alias: 'dia-chi',
          Title: 'Địa chỉ',
          Intro: null,
          Html: '<h5>DATACOM TẠI TP HỒ CH&Iacute; MINH</h5>\n\n<div><label>52 Huỳnh Khương Ninh, P.&ETH;a Kao, Q1, Tp Hồ Ch&iacute; Minh</label></div>\n\n<div><label>Website:&nbsp;<a href="https://datacom.vn/" title="datacom.vn">https://datacom.vn</a>&nbsp;- Email:&nbsp;<a href="mailto:contect@datacom.vn" title="contect@datacom.vn">contect@datacom.vn</a>&nbsp;</label></div>\n\n<div><label>Tel: (+024) 7300 6091 - Fax: (+028) 38 48 7160</label></div>\n',
          Image: '/images/content/DC10899/s30ez2kc.png',
          Highlight: false,
          Position: 0,
          View: 0,
          DayNum: 0,
          Rate: 2,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-06-05T15:00:24.38',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: 'F5982BB8-1B4E-4E26-A661-92A0E765C4A6',
          Index: 331,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'EE626B9F-D336-4410-89A9-2C2E55307630',
          Language: 'vi',
          Alias: 'lien-he',
          Title: 'Liên hệ',
          Intro: 'CÔNG TY CPDT & CN DATACOM VIỆT NAM',
          Html: '<div class="row mt-4">\n<div class="col-md-6">\n<p class="fs-20 fw-bold"><strong>Văn ph&ograve;ng DATACOM VietNam tại H&agrave; Nội</strong></p>\n\n<p class="d-flex align-items-center column-gap-3 mt-3">Tầng 3, t&ograve;a nh&agrave; NEWS BUILDING, ng&otilde; 27 Đại Cồ Việt, Quận Hai B&agrave; Trưng, H&agrave; Nội</p>\n\n<p class="d-flex align-items-center column-gap-3 mt-3">Contact: 1900-0310 | Fax: 1900-0310</p>\n\n<p class="d-flex align-items-center column-gap-3 mt-3">Email: demo@datacom.vn</p>\n\n<div class="w-100 mt-3"><iframe allowfullscreen="" height="400" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d51591.29452174047!2d105.83639964362187!3d20.97724478613849!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ac1eb17075a1%3A0xb1f717592512c549!2zSGFpIELDoCBUcsawbmcsIEjDoCBO4buZaSwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2s!4v1715670967304!5m2!1svi!2s" style="width: 100%; border-radius: 10px;"></iframe></div>\n</div>\n\n<div class="col-md-6">\n<p class="fs-20 fw-bold"><strong>Văn ph&ograve;ng DATACOM tại Nhật Bản</strong></p>\n\n<p class="d-flex align-items-center column-gap-3 mt-3">〒542-0082 大阪府大阪市中央区島之内1-13-3 おおきに東心斎橋ビル321</p>\n\n<p class="d-flex align-items-center column-gap-3 mt-3">Contact: (+81) 70-1810-123 | Fax: (+81) 06-7181-1234</p>\n\n<p class="d-flex align-items-center column-gap-3 mt-3">Email: demo@datacom.vn</p>\n\n<div class="w-100 mt-3"><iframe allowfullscreen="" height="400" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d80936.25938923292!2d135.5600584931606!3d34.70412170228669!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6000e73e444c5ffd%3A0xaae76d82a98abfd0!2sOokini%20Higashi-Shinsaibashi%20Building%2C%20303%2C%201-ch%C5%8Dme-13-3%20Shimanouchi%2C%20Chuo%20Ward%2C%20Osaka%2C%20542-0082%2C%20Nh%E1%BA%ADt%20B%E1%BA%A3n!5e0!3m2!1svi!2s!4v1715671237110!5m2!1svi!2s" style="width: 100%; border-radius: 10px;"></iframe></div>\n</div>\n</div>\n\n<div class="row mt-5 mb-4">\n<h1 class="page-title text-uppercase">Th&ocirc;ng Tin Li&ecirc;n Hệ</h1>\n\n<div class="row row-gap-4 mt-3">\n<div class="col-md-4">\n<div class="d-flex gap-2">&nbsp;\n<div>\n<div class="fs-20"><span>Hotline</span> <span class="fw-bold" style="color: #F58A21">(+84) 338-320-320</span></div>\n<span>Từ 8h &ndash; 22h (thứ 2 - Thứ 7)</span></div>\n</div>\n</div>\n\n<div class="col-md-4">\n<div class="d-flex gap-2">&nbsp;\n<div>\n<div class="fs-20"><span>Hotline</span> <span class="fw-bold" style="color: #F58A21">(+84) 338-320-320</span></div>\n<span>Từ 8h &ndash; 22h (thứ 2 - Thứ 7)</span></div>\n</div>\n</div>\n\n<div class="col-md-4">\n<div class="d-flex gap-2">&nbsp;\n<div>\n<div class="fs-20"><span>Hotline</span> <span class="fw-bold" style="color: #F58A21">(+84) 338-320-320</span></div>\n<span>Từ 8h &ndash; 22h (thứ 2 - Thứ 7)</span></div>\n</div>\n</div>\n</div>\n</div>\n',
          Image: '/images/content/DC10899/egcxdpaf.png',
          Highlight: false,
          Position: 0,
          View: 0,
          DayNum: 0,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-05-28T16:53:43.22',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: '7143F7C4-9A02-4820-9476-336EB26CEC38',
          Index: 329,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'EE626B9F-D336-4410-89A9-2C2E55307630',
          Language: 'vi',
          Alias: 'quyen-rieng-tu',
          Title: 'Quyền riêng tư',
          Intro: null,
          Html: '<p>1. Cam kết của Datacom về bảo vệ th&ocirc;ng tin c&aacute; nh&acirc;n</p>\n\n<p>Hiểu r&otilde; tầm quan trọng của việc bảo vệ th&ocirc;ng tin c&aacute; nh&acirc;n, Datacom cam kết tu&acirc;n thủ c&aacute;c quy định về bảo mật được quy định bởi ph&aacute;p luật\u202FViệt Nam v&agrave; c&aacute;c quy định của ph&aacute;p luật c&aacute;c nước li&ecirc;n quan, v&agrave; thực hiện c&aacute;c biện ph&aacute;p th&iacute;ch hợp nhằm đảm bảo dữ liệu qu&yacute; kh&aacute;ch cung cấp được bảo mật v&agrave; bảo vệ an to&agrave;n.</p>\n\n<p>&nbsp;</p>\n\n<p>Ch&iacute;nh s&aacute;ch Bảo Mật Th&ocirc;ng Tin c&ocirc;ng bố tr&ecirc;n website n&agrave;y giải th&iacute;ch l&yacute; do v&agrave; c&aacute;ch thức Datacom thu thập, ghi, thiết lập, cấu tr&uacute;c, lưu trữ, điều chỉnh hoặc sửa đổi, kh&ocirc;i phục, tra cứu, sử dụng, tiết lộ, đồng chỉnh hoặc kết hợp, hạn chế, x&oacute;a hoặc hủy th&ocirc;ng tin c&aacute; nh&acirc;n qu&yacute; kh&aacute;ch cung cấp trong qu&aacute; tr&igrave;nh thực hiện h&agrave;nh tr&igrave;nh, mua, sử dụng dịch vụ, truy cập Website, sử dụng ứng dụng Datacom tr&ecirc;n điện thoại hoặc tương t&aacute;c với Datacom. Ch&iacute;nh s&aacute;ch Bảo Mật Th&ocirc;ng Tin n&agrave;y cũng hướng dẫn qu&yacute; kh&aacute;ch c&aacute;ch thức thực hiện c&aacute;c quyền li&ecirc;n quan đến dữ liệu c&aacute; nh&acirc;n của m&igrave;nh.</p>\n\n<p>&nbsp;</p>\n\n<p>Trong một số trường hợp, Datacom đ&oacute;ng vai tr&ograve; l&agrave; đơn vị đồng kiểm so&aacute;t dữ liệu c&aacute; nh&acirc;n với c&aacute;c c&ocirc;ng ty kh&aacute;c như trường hợp khi Datacom cung cấp dịch vụ h&agrave;ng kh&ocirc;ng hợp t&aacute;c với c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng kh&aacute;c (th&ocirc;ng qua thỏa thuận chia sẻ m&atilde; code hoặc thỏa thuận li&ecirc;n chặng) hoặc khi cung cấp dịch vụ lữ h&agrave;nh hợp t&aacute;c với c&aacute;c kh&aacute;ch sạn, ng&acirc;n h&agrave;ng, c&ocirc;ng ty bảo hiểm lữ h&agrave;nh&hellip;.</p>\n\n<p>&nbsp;</p>\n\n<p>Đối với c&aacute;c hoạt động n&agrave;y, Datacom v&agrave; c&aacute;c đối t&aacute;c c&ugrave;ng chịu tr&aacute;ch nhiệm trong việc xử l&yacute; dữ liệu c&aacute; nh&acirc;n của qu&yacute; kh&aacute;ch. Datacom v&agrave; c&aacute;c đối t&aacute;c đ&atilde; tiến h&agrave;nh x&aacute;c định tr&aacute;ch nhiệm của từng b&ecirc;n trong việc tu&acirc;n thủ c&aacute;c nghĩa vụ về bảo mật th&ocirc;ng tin khi xử l&yacute; dữ liệu c&aacute; nh&acirc;n li&ecirc;n quan đến c&aacute;c hoạt động n&agrave;y.</p>\n\n<p>&nbsp;</p>\n\n<p>Theo đ&oacute;, bất kỳ khi n&agrave;o qu&yacute; kh&aacute;ch muốn sử dụng quyền li&ecirc;n quan đến dữ liệu c&aacute; nh&acirc;n của m&igrave;nh như quyền truy cập, chỉnh sửa, x&oacute;a, hạn chế, phản đối, di chuyển dữ liệu hoặc r&uacute;t lại sự đồng &yacute;, hoặc khi qu&yacute; kh&aacute;ch c&oacute; bất cứ thắc mắc hay khiếu nại n&agrave;o về việc xử l&yacute; dữ liệu c&aacute; nh&acirc;n của m&igrave;nh, qu&yacute; kh&aacute;ch c&oacute; thể li&ecirc;n hệ Datacom hoặc c&aacute;c đối t&aacute;c của Datacom. Datacom v&agrave; c&aacute;c đối t&aacute;c sẽ hỗ trợ lẫn nhau để đảm bảo qu&yacute; kh&aacute;ch c&oacute; thể thực hiện c&aacute;c quyền của m&igrave;nh cũng như trả lời thắc mắc v&agrave; giải quyết khiếu nại của qu&yacute; kh&aacute;ch.</p>\n\n<p>&nbsp;</p>\n\n<p>Cụ thể, Datacom tu&acirc;n thủ c&aacute;c nguy&ecirc;n tắc sau:</p>\n\n<p>&nbsp;</p>\n\n<p>Dữ liệu c&aacute; nh&acirc;n của qu&yacute; kh&aacute;ch được xử l&yacute; một c&aacute;ch hợp ph&aacute;p, c&ocirc;ng bằng, minh bạch.</p>\n\n<p>&nbsp;</p>\n\n<p>Dữ liệu c&aacute; nh&acirc;n của qu&yacute; kh&aacute;ch được thu thập với mục đ&iacute;ch cụ thể, r&otilde; r&agrave;ng, hợp ph&aacute;p v&agrave; sẽ kh&ocirc;ng được xử l&yacute; ngo&agrave;i c&aacute;c mục đ&iacute;ch đ&atilde; n&ecirc;u.</p>\n\n<p>&nbsp;</p>\n\n<p>Dữ liệu c&aacute; nh&acirc;n của qu&yacute; kh&aacute;ch được lưu trữ một c&aacute;ch hợp l&yacute;, ph&ugrave; hợp v&agrave; trong phạm vi cần thiết cho c&aacute;c mục đ&iacute;ch xử l&yacute;</p>\n\n<p>&nbsp;</p>\n\n<p>Dữ liệu c&aacute; nh&acirc;n của qu&yacute; kh&aacute;ch l&agrave; ch&iacute;nh x&aacute;c, được cập nhật v&agrave; c&aacute;c dữ liệu kh&ocirc;ng ch&iacute;nh x&aacute;c li&ecirc;n quan đến mục đ&iacute;ch xử l&yacute; sẽ được x&oacute;a hoặc sửa kịp thời</p>\n\n<p>&nbsp;</p>\n\n<p>Datacom &aacute;p dụng c&aacute;c biện ph&aacute;p kỹ thuật v&agrave; tổ chức ph&ugrave; hợp nhằm đảm bảo t&iacute;nh an to&agrave;n của dữ liệu c&aacute; nh&acirc;n ở mức th&iacute;ch hợp, bao gồm c&aacute;c biện ph&aacute;p bảo vệ khỏi sự truy cập tr&aacute;i ph&eacute;p hoặc bất hợp ph&aacute;p dữ liệu c&aacute; nh&acirc;n v&agrave; sự ph&aacute; hủy, mất, thiệt hại ngo&agrave;i &yacute; muốn.</p>\n\n<p>&nbsp;</p>\n\n<p>Ngo&agrave;i ra, Datacom đảm bảo rằng c&aacute;c nh&agrave; thầu phụ (nh&agrave; cung cấp dịch vụ, nh&agrave; cung cấp kh&aacute;c, v.v&hellip;) cũng tu&acirc;n thủ c&ugrave;ng mức bảo vệ dữ liệu c&aacute; nh&acirc;n trong c&aacute;c hợp đồng k&yacute; kết với Datacom.</p>\n',
          Image: '/images/content/DC10899/lkr4nge3.png',
          Highlight: false,
          Position: 0,
          View: 0,
          DayNum: 0,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-05-28T16:44:25.323',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: 'D3AAFBFF-0A48-427E-BEDE-F9159059860D',
          Index: 328,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'EE626B9F-D336-4410-89A9-2C2E55307630',
          Language: 'vi',
          Alias: 'chinh-sach-bao-ve-hanh-khach',
          Title: 'Chính sách bảo vệ hành khách',
          Intro: null,
          Html: '<p>Ch&iacute;nh s&aacute;ch bảo vệ h&agrave;nh kh&aacute;ch</p>\n\n<p>Với th&ocirc;ng đi&ecirc;̣p: con đường ph&aacute;t triển của Datacom lu&ocirc;n đặt trọng t&acirc;m v&agrave;o trải nghiệm của kh&aacute;ch h&agrave;ng, Chúng t&ocirc;i lu&ocirc;n mong muốn mang đến cho h&agrave;nh kh&aacute;ch kh&ocirc;ng chỉ một chuyến bay, m&agrave; c&ograve;n l&agrave; cảm x&uacute;c về một h&agrave;nh tr&igrave;nh trải nghiệm c&aacute;c dịch vụ định hướng 5 sao theo ti&ecirc;u chuẩn quốc tế, sang trọng, đẳng cấp với ti&ecirc;u ch&iacute;: Hiếu kh&aacute;ch, &Acirc;n cần, Tận t&acirc;m v&agrave; Tr&aacute;ch nhiệm. Đ&ecirc;̉ đảm bảo những lợi ích của hành khách, chúng t&ocirc;i cung c&acirc;́p các th&ocirc;ng tin v&ecirc;̀ Chính sách phục vụ hành khách trong trường hợp b&acirc;́t thường khi thực hi&ecirc;̣n các chuy&ecirc;́n bay cùng Datacom như sau:</p>\n\n<p>1. Trường hợp hành khách đã có vé và đã được xác nh&acirc;̣n ch&ocirc;̃ tr&ecirc;n chuy&ecirc;́n bay nhưng bị từ ch&ocirc;́i v&acirc;̣n chuy&ecirc;̉n do l&ocirc;̃i của Datacom</p>\n\n<p>Trong một số trường hợp, những hành khách đã có vé và đã được xác nh&acirc;̣n ch&ocirc;̃ tr&ecirc;n chuy&ecirc;́n bay có th&ecirc;̉ bị từ ch&ocirc;́i v&acirc;̣n chuy&ecirc;̉n do l&ocirc;̃i của Datacom. Ví dụ trong trường hợp số lượng h&agrave;nh kh&aacute;ch l&agrave;m thủ tục vượt qu&aacute; số ghế thực tế của m&aacute;y bay. Trong những trường hợp này, đ&ocirc;́i với các chuyến bay xuất ph&aacute;t trong l&atilde;nh thổ Việt Nam, Datacom sẽ thu x&ecirc;́p chuy&ecirc;́n bay thay th&ecirc;́, đ&ocirc;̀ng thời thực hi&ecirc;̣n các nghĩa vụ của Người v&acirc;̣n chuy&ecirc;̉n như b&ocirc;̀i thường ứng trước kh&ocirc;ng hoàn lại cho hành khách theo chính sách của Datacom nhưng kh&ocirc;ng th&acirc;́p hơn mức quy định tại Th&ocirc;ng tư số 14/2015/TT-BGTVT đ&atilde; được sửa đổi, bổ sung một số điều bởi Th&ocirc;ng tư số 27/2017/TT-BGTVT ng&agrave;y 25/8/2017 của Bộ Giao Th&ocirc;ng Vận Tải quy định về việc bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại trong vận chuyển h&agrave;nh kh&aacute;ch bằng đường h&agrave;ng kh&ocirc;ng. Đối với c&aacute;c chuyến bay ngo&agrave;i l&atilde;nh thổ Việt Nam, sẽ theo quy định của nước sở tại hoặc quy định của ch&uacute;ng t&ocirc;i.</p>\n\n<p>Datacom được mi&ecirc;̃n trừ nghĩa vụ bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại trong c&aacute;c trường hợp từ chối vận chuyển h&agrave;nh kh&aacute;ch c&oacute; v&eacute; v&agrave; đ&atilde; được x&aacute;c nhận chỗ tr&ecirc;n chuyến bay hoặc đang trong h&agrave;nh tr&igrave;nh theo quy định tại Điều 146 Luật H&agrave;ng kh&ocirc;ng d&acirc;n dụng Việt Nam, cụ thể như sau:</p>\n\n<p>&ndash; Do t&igrave;nh trạng sức khỏe của h&agrave;nh kh&aacute;ch m&agrave; Chúng t&ocirc;i nhận thấy việc vận chuyển hoặc vận chuyển tiếp sẽ g&acirc;y nguy hại cho h&agrave;nh kh&aacute;ch đ&oacute;, cho những người kh&aacute;c trong t&agrave;u bay hoặc g&acirc;y nguy hại cho chuyến bay.</p>\n\n<p>&ndash; Để ngăn ngừa l&acirc;y lan dịch bệnh.</p>\n\n<p>&ndash; H&agrave;nh kh&aacute;ch kh&ocirc;ng chấp h&agrave;nh quy định về bảo đảm an to&agrave;n h&agrave;ng kh&ocirc;ng, an ninh h&agrave;ng kh&ocirc;ng, khai th&aacute;c vận chuyển h&agrave;ng kh&ocirc;ng, xử phạt vi phạm h&agrave;nh ch&iacute;nh về h&agrave;ng kh&ocirc;ng d&acirc;n dụng.</p>\n\n<p>&ndash; H&agrave;nh kh&aacute;ch c&oacute; h&agrave;nh vi l&agrave;m mất trật tự c&ocirc;ng cộng, uy hiếp an to&agrave;n bay hoặc g&acirc;y ảnh hưởng đến t&iacute;nh mạng, sức khỏe, t&agrave;i sản của người kh&aacute;c.</p>\n\n<p>&ndash; H&agrave;nh kh&aacute;ch trong t&igrave;nh trạng say rượu, bia hoặc c&aacute;c chất k&iacute;ch th&iacute;ch kh&aacute;c m&agrave; kh&ocirc;ng l&agrave;m chủ được h&agrave;nh vi.</p>\n\n<p>&ndash; V&igrave; l&yacute; do an ninh được cơ quan c&oacute; thẩm quyền th&ocirc;ng b&aacute;o.</p>\n\n<p>&ndash; Theo y&ecirc;u cầu của cơ quan nh&agrave; nước c&oacute; thẩm quyền.</p>\n\n<p>Phương thức v&agrave; thời hạn bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại: Datacom c&oacute; thể bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại cho h&agrave;nh kh&aacute;ch bằng c&aacute;c phương thức sau đ&acirc;y:</p>\n\n<p>&ndash; Tiền mặt;</p>\n\n<p>&ndash; Chuyển khoản ng&acirc;n h&agrave;ng hoặc th&ocirc;ng qua c&aacute;c dịch vụ trung gian thanh to&aacute;n ph&ugrave; hợp kh&aacute;c trong trường hợp h&agrave;nh kh&aacute;ch y&ecirc;u cầu. Đối với phương thức n&agrave;y, vi&ecirc;̣c bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại sẽ được thực hi&ecirc;̣n trong v&ograve;ng 14 ng&agrave;y l&agrave;m việc kể từ ng&agrave;y nhận được y&ecirc;u cầu của h&agrave;nh kh&aacute;ch;</p>\n\n<p>&ndash; V&eacute; miễn cước, chứng từ bồi ho&agrave;n để sử dụng tiếp dịch vụ của người vận chuyển hoặc c&aacute;c dịch vụ miễn ph&iacute; kh&aacute;c trong trường hợp h&agrave;nh kh&aacute;ch chấp thuận.</p>\n\n<p>Địa đi&ecirc;̉m Datacom thực hi&ecirc;̣n b&ocirc;̀i thường ứng trước kh&ocirc;ng hoàn lại cho hành khách:</p>\n\n<p>&ndash; Cảng h&agrave;ng kh&ocirc;ng nơi h&agrave;nh kh&aacute;ch bị từ chối vận chuyển;</p>\n\n<p>&ndash; Chi nh&aacute;nh hoặc văn ph&ograve;ng đại diện được Datacom chỉ định theo thỏa thuận với h&agrave;nh kh&aacute;ch trong trường hợp h&agrave;nh kh&aacute;ch l&agrave;m thủ tục tại địa điểm kh&aacute;c ngo&agrave;i cảng h&agrave;ng kh&ocirc;ng;</p>\n\n<p>&ndash; V&agrave;o t&agrave;i khoản do h&agrave;nh kh&aacute;ch cung cấp trong trường hợp lựa chọn phương thức Chuyển khoản ng&acirc;n h&agrave;ng hoặc th&ocirc;ng qua c&aacute;c dịch vụ trung gian thanh to&aacute;n ph&ugrave; hợp kh&aacute;c.</p>\n\n<p>2. Trường hợp hành khách đã có vé và đã được xác nh&acirc;̣n ch&ocirc;̃ tr&ecirc;n chuy&ecirc;́n bay nhưng chuyến bay bị chậm, gi&aacute;n đoạn, hủy chuyến, khởi hành sớm</p>\n\n<p>2.1. Trường hợp chậm chuyến, gi&aacute;n đoạn vận chuyển theo kế hoạch 15 ph&uacute;t trở l&ecirc;n và khởi hành sớm, Datacom sẽ:</p>\n\n<p>&ndash; Th&ocirc;ng b&aacute;o cho h&agrave;nh kh&aacute;ch c&aacute;c th&ocirc;ng tin li&ecirc;n quan đến chuyến bay, cụ thể như sau: số hiệu chuyến bay v&agrave; chặng bay; l&yacute; do của việc chậm chuyến, gi&aacute;n đoạn vận chuyển; thời gian cất c&aacute;nh dự kiến hoặc kế hoạch bay thay thế; kế hoạch phục vụ h&agrave;nh kh&aacute;ch; bộ phận trợ gi&uacute;p h&agrave;nh kh&aacute;ch (vị tr&iacute;, dấu hiệu nhận biết);</p>\n\n<p>&ndash; Xin lỗi h&agrave;nh kh&aacute;ch.</p>\n\n<p>2.2. Trường hợp h&agrave;nh kh&aacute;ch đ&atilde; được x&aacute;c nhận chỗ tr&ecirc;n chuyến bay nhưng việc vận chuyển bị chậm, gi&aacute;n đoạn, hủy chuyến, khởi hành sớm Datacom sẽ:</p>\n\n<p>a. Cung cấp các dịch vụ tại s&acirc;n bay</p>\n\n<p>&ndash; Thời gian ch&acirc;̣m từ 02 giờ: Phục vụ nước uống</p>\n\n<p>&ndash; Thời gian ch&acirc;̣m từ 03 giờ trở l&ecirc;n: Phục vụ ăn, u&ocirc;́ng</p>\n\n<p>&ndash; Thời gian chậm từ 06 giờ trở l&ecirc;n (từ 07 giờ đến trước 22 giờ): bố tr&iacute; nơi nghỉ ph&ugrave; hợp với điều kiện thực tế của cảng h&agrave;ng kh&ocirc;ng;</p>\n\n<p>&ndash; Thời gian chậm 06 giờ trở l&ecirc;n (từ 22 giờ h&ocirc;m trước đến trước 07 giờ ng&agrave;y h&ocirc;m sau): bố tr&iacute; chỗ ngủ, nghỉ ph&ugrave; hợp với điều kiện thực tế của địa phương hoặc giải ph&aacute;p thay thế nếu được sự đồng &yacute; của h&agrave;nh kh&aacute;ch;</p>\n\n<p>b. Chuyển đổi h&agrave;nh tr&igrave;nh của h&agrave;nh kh&aacute;ch trong phạm vi cung cấp dịch vụ của Datacom để h&agrave;nh kh&aacute;ch tới được điểm cuối của h&agrave;nh tr&igrave;nh một c&aacute;ch nhanh ch&oacute;ng v&agrave; thuận tiện nhất.</p>\n\n<p>c. B&ocirc;̀i thường ứng trước kh&ocirc;ng hoàn lại</p>\n\n<p>1) Mức b&ocirc;̀i thường ứng trước kh&ocirc;ng hoàn lại</p>\n\n<p>&ndash; Trong trường hợp chậm chuyến k&eacute;o d&agrave;i, hủy chuyến tr&ecirc;n c&aacute;c chuyến bay xuất ph&aacute;t trong l&atilde;nh thổ Việt Nam, Datacom sẽ b&ocirc;̀i thường ứng trước kh&ocirc;ng hoàn lại cho hành khách theo mức quy định tại Th&ocirc;ng tư số 14/2015/TT-BGTVT đ&atilde; được sửa đổi, bổ sung một số điều bởi Th&ocirc;ng tư số 27/2017/TT-BGTVT ng&agrave;y 25/8/2017 của Bộ Giao Th&ocirc;ng Vận Tải quy định về việc bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại trong vận chuyển h&agrave;nh kh&aacute;ch bằng đường h&agrave;ng kh&ocirc;ng.</p>\n\n<p>&ndash; Đối với c&aacute;c chuyến bay ngo&agrave;i l&atilde;nh thổ Việt Nam, sẽ theo quy định của nước sở tại hoặc quy định của ch&uacute;ng t&ocirc;i.</p>\n\n<p>2) Datacom được miễn trừ nghĩa vụ bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại trong trường hợp hủy chuyến bay hoặc chuyến bay bị chậm k&eacute;o d&agrave;i v&igrave; một trong c&aacute;c l&yacute; do sau đ&acirc;y:</p>\n\n<p>&ndash; Điều kiện thời tiết ảnh hưởng đến khai th&aacute;c an to&agrave;n chuyến bay.</p>\n\n<p>&ndash; Nguy cơ an ninh ảnh hưởng đến khai th&aacute;c an to&agrave;n chuyến bay.</p>\n\n<p>&ndash; Chuyến bay kh&ocirc;ng thể thực hiện hoặc bị chậm k&eacute;o d&agrave;i theo quyết định của cơ quan nh&agrave; nước c&oacute; thẩm quyền.</p>\n\n<p>&ndash; Do những vấn đề về y tế của h&agrave;nh kh&aacute;ch (bị ốm nặng hoặc chết sau khi đ&atilde; l&ecirc;n t&agrave;u bay).</p>\n\n<p>&ndash; T&agrave;u bay theo lịch dự kiến để khai th&aacute;c chuyến bay bị ph&aacute; hoại hoặc đội t&agrave;u bay bị ph&aacute; hoại.</p>\n\n<p>&ndash; Do xung đột vũ trang, mất ổn định ch&iacute;nh trị, đ&igrave;nh c&ocirc;ng l&agrave;m ảnh hưởng đến chuyến bay.</p>\n\n<p>&ndash; Trong trường hợp kết cấu hạ tầng h&agrave;ng kh&ocirc;ng, dịch vụ bảo đảm hoạt động bay kh&ocirc;ng đảm bảo cho việc thực hiện chuyến bay.</p>\n\n<p>&ndash; Sự cố kỹ thuật xảy ra trong qu&aacute; tr&igrave;nh khai th&aacute;c t&agrave;u bay, t&iacute;nh từ thời điểm người chỉ huy t&agrave;u bay k&yacute; tiếp nhận t&agrave;u bay sẵn s&agrave;ng thực hiện chuyến bay cho đến khi kết th&uacute;c chuyến bay.</p>\n\n<p>&ndash; H&agrave;nh kh&aacute;ch được bố tr&iacute; h&agrave;nh tr&igrave;nh tới điểm đến theo kế hoạch bằng chuyến bay kh&aacute;c với thời gian đến kh&ocirc;ng qu&aacute; 4 giờ so với thời gian đến dự kiến của chuyến bay đ&atilde; được x&aacute;c nhận chỗ.</p>\n\n<p>&ndash; H&agrave;nh kh&aacute;ch được bố tr&iacute; tới điểm đến của h&agrave;nh tr&igrave;nh với thời gian đến kh&ocirc;ng qu&aacute; 6 giờ so với thời gian đến dự kiến của chuyến bay nối chuyến trong trường hợp điểm đến theo kế hoạch của chuyến bay l&agrave; điểm nối chuyến trong h&agrave;nh tr&igrave;nh của h&agrave;nh kh&aacute;ch.</p>\n\n<p>&ndash; C&aacute;c trường hợp bất khả kh&aacute;ng kh&aacute;c.</p>\n\n<p>&ndash; Datacom được miễn trừ nghĩa vụ bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại cho h&agrave;nh kh&aacute;ch nếu người vận chuyển chứng minh được một trong c&aacute;c trường hợp sau:</p>\n\n<p>Đ&atilde; th&ocirc;ng b&aacute;o bằng lời n&oacute;i, tin nhắn, thư điện tử cho h&agrave;nh kh&aacute;ch về việc hủy chuyến bay, chuyến bay bị chậm k&eacute;o d&agrave;i &iacute;t nhất 24 giờ trước giờ khởi h&agrave;nh dự kiến theo địa chỉ như số điện thoại di động, số điện thoại cố định, thư điện tử hoặc số điện thoại của người th&acirc;n trong trường hợp kh&ocirc;ng li&ecirc;n lạc được trực tiếp; trường hợp thực hiện cuộc gọi bằng điện thoại, phải thực hiện cuộc gọi trong v&ograve;ng 7h đến 22h với tần suất l&agrave; 02 cuộc, c&aacute;ch nhau 20 ph&uacute;t nếu cuộc gọi đầu ti&ecirc;n kh&ocirc;ng li&ecirc;n hệ được.</p>\n\n<p>H&agrave;nh kh&aacute;ch kh&ocirc;ng đăng k&yacute; th&ocirc;ng tin li&ecirc;n lạc theo quy định</p>\n\n<p>Kh&ocirc;ng li&ecirc;n hệ được với h&agrave;nh kh&aacute;ch theo th&ocirc;ng tin li&ecirc;n lạc đ&atilde; đăng k&yacute;</p>\n\n<p>&ndash; Datacom được miễn trừ nghĩa vụ trả tiền bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại trong trường hợp h&agrave;nh kh&aacute;ch được vận chuyển miễn ph&iacute;; h&agrave;nh kh&aacute;ch được vận chuyển theo gi&aacute; giảm &aacute;p dụng đối với nh&acirc;n vi&ecirc;n h&atilde;ng h&agrave;ng kh&ocirc;ng (Industry Discount Ticket), nh&acirc;n vi&ecirc;n đại l&yacute; của h&atilde;ng h&agrave;ng kh&ocirc;ng (Agent Discount), đối t&aacute;c, bạn h&agrave;ng sử dụng v&eacute; miễn giảm cước.</p>\n\n<p>&ndash; Datacom được miễn trừ nghĩa vụ trả tiền bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại trong trường hợp h&agrave;nh kh&aacute;ch kh&ocirc;ng c&oacute; mặt l&agrave;m thủ tục h&agrave;ng kh&ocirc;ng tại cảng h&agrave;ng kh&ocirc;ng hoặc địa điểm kh&aacute;c theo thỏa thuận với Datacom.</p>\n\n<p>&ndash; Datacom được miễn trừ nghĩa vụ trả tiền bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại trong trường hợp h&agrave;nh kh&aacute;ch tự nguyện từ bỏ x&aacute;c nhận.</p>\n\n<p>3) Phương thức v&agrave; thời hạn bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại</p>\n\n<p>&ndash; Tiền mặt;</p>\n\n<p>&ndash; Chuyển khoản ng&acirc;n h&agrave;ng hoặc th&ocirc;ng qua c&aacute;c dịch vụ trung gian thanh to&aacute;n ph&ugrave; hợp kh&aacute;c trong trường hợp h&agrave;nh kh&aacute;ch y&ecirc;u cầu. Đối với phương thức n&agrave;y, vi&ecirc;̣c bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại sẽ được thực hi&ecirc;̣n trong v&ograve;ng 14 ng&agrave;y l&agrave;m việc kể từ ng&agrave;y nhận được y&ecirc;u cầu của h&agrave;nh kh&aacute;ch;</p>\n\n<p>&ndash; V&eacute; miễn cước, chứng từ bồi ho&agrave;n để sử dụng tiếp dịch vụ của người vận chuyển hoặc c&aacute;c dịch vụ miễn ph&iacute; kh&aacute;c trong trường hợp h&agrave;nh kh&aacute;ch chấp thuận.</p>\n\n<p>4) Địa đi&ecirc;̉m Datacom thực hi&ecirc;̣n b&ocirc;̀i thường ứng trước kh&ocirc;ng hoàn lại cho hành khách</p>\n\n<p>&ndash; Tại cảng h&agrave;ng kh&ocirc;ng nơi chuyến bay bị hủy (đ&ocirc;́i với chuy&ecirc;́n bay hủy) hoặc tại cảng h&agrave;ng kh&ocirc;ng nơi chuyến bay cất c&aacute;nh hoặc hạ c&aacute;nh (đ&ocirc;́i với chuy&ecirc;́n bay bị ch&acirc;̣m kéo dài)</p>\n\n<p>&ndash; Chi nh&aacute;nh hoặc văn ph&ograve;ng đại diện được Datacom chỉ định theo thỏa thuận với h&agrave;nh kh&aacute;ch trong trường hợp h&agrave;nh kh&aacute;ch l&agrave;m thủ tục tại địa điểm kh&aacute;c ngo&agrave;i cảng h&agrave;ng kh&ocirc;ng;</p>\n\n<p>&ndash; V&agrave;o t&agrave;i khoản do h&agrave;nh kh&aacute;ch cung cấp trong trường hợp lựa chọn phương thức Chuyển khoản ng&acirc;n h&agrave;ng hoặc th&ocirc;ng qua c&aacute;c dịch vụ trung gian thanh to&aacute;n ph&ugrave; hợp kh&aacute;c.</p>\n\n<p>5) Thời hạn bồi thường: Kh&ocirc;ng qu&aacute; 14 ng&agrave;y l&agrave;m việc kể từ ng&agrave;y chuyến bay bị hủy hoặc chậm k&eacute;o d&agrave;i. Trong trường hợp h&agrave;nh kh&aacute;ch chưa nhận được bồi thường, h&agrave;nh kh&aacute;ch vui l&ograve;ng gửi văn bản y&ecirc;u cầu trong thời hạn 90 ng&agrave;y kể từ ng&agrave;y chuyến bay dự kiến cất c&aacute;nh. Ch&uacute;ng t&ocirc;i sẽ trả lời hoặc thực hiện bồi thường trong v&ograve;ng 7 ng&agrave;y kể từ ng&agrave;y nhận được văn bản.</p>\n\n<p>d. Ho&agrave;n trả tiền v&eacute; cho h&agrave;nh kh&aacute;ch: trong trường hợp chuyến bay chậm từ 03 giờ trở l&ecirc;n, chuy&ecirc;́n bay hủy kh&ocirc;ng có chuy&ecirc;́n bay thay th&ecirc;́ hoặc chuy&ecirc;́n bay khởi hành sớm d&acirc;̃n đ&ecirc;́n vi&ecirc;̣c h&agrave;nh kh&aacute;ch đ&atilde; x&aacute;c nhận chỗ nhưng kh&ocirc;ng thực hiện được chuyến bay: Datacom sẽ ho&agrave;n trả to&agrave;n bộ tiền v&eacute; hoặc ho&agrave;n trả tiền phần v&eacute; chưa sử dụng theo sự lựa chọn của h&agrave;nh kh&aacute;ch tại cảng h&agrave;ng kh&ocirc;ng hoặc tại c&aacute;c văn ph&ograve;ng đại diện, chi nh&aacute;nh hoặc đại l&yacute; b&aacute;n v&eacute; do Datacom chỉ định. Việc ho&agrave;n v&eacute; cho h&agrave;nh kh&aacute;ch được quy định như sau:</p>\n\n<p>&ndash; Miễn trừ điều kiện hạn chế về ho&agrave;n v&eacute; v&agrave; ph&iacute; ho&agrave;n v&eacute; (nếu c&oacute;);</p>\n\n<p>&ndash; V&eacute; ho&agrave;n to&agrave;n chưa được sử dụng, khoản chi ho&agrave;n sẽ bằng số tiền v&eacute; m&agrave; h&agrave;nh kh&aacute;ch đ&atilde; trả; tiền v&eacute; bao gồm c&aacute;c khoản: gi&aacute; dịch vụ vận chuyển; c&aacute;c khoản thuế, ph&iacute; do Nh&agrave; nước quy định, gi&aacute; dịch vụ soi chiếu an ninh, gi&aacute; phục vụ h&agrave;nh kh&aacute;ch tại cảng h&agrave;ng kh&ocirc;ng, s&acirc;n bay m&agrave; h&atilde;ng h&agrave;ng kh&ocirc;ng thu hộ; v&agrave; c&aacute;c khoản phụ thu kh&aacute;c c&oacute; li&ecirc;n quan theo h&oacute;a đơn hợp ph&aacute;p do h&agrave;nh kh&aacute;ch cung cấp;</p>\n\n<p>&ndash; V&eacute; đ&atilde; được sử dụng một phần, khoản chi ho&agrave;n sẽ kh&ocirc;ng thấp hơn ch&ecirc;nh lệch giữa tiền v&eacute; đ&atilde; trả v&agrave; tiền v&eacute;, c&aacute;c dịch vụ kh&aacute;c đ&atilde; sử dụng cho h&agrave;nh tr&igrave;nh của h&agrave;nh kh&aacute;ch.</p>\n\n<p>H&agrave;nh kh&aacute;ch c&oacute; thể tham khảo th&ecirc;m th&ocirc;ng tin tại c&aacute;c quy định ph&aacute;p luật li&ecirc;n quan dưới đ&acirc;y:</p>\n\n<p>&ndash; Luật H&agrave;ng kh&ocirc;ng d&acirc;n dụng Việt Nam</p>\n\n<p>&ndash; Th&ocirc;ng tư 36/2014/TT-BGTVT ng&agrave;y 29/8/2014 của Bộ Giao th&ocirc;ng vận tải quy định chất lượng dịch vụ h&agrave;nh kh&aacute;ch tại cảng h&agrave;ng kh&ocirc;ng</p>\n\n<p>&ndash; Th&ocirc;ng tư số 81/2014/TT-BGTVT ng&agrave;y 30/12/2014 của Bộ Giao th&ocirc;ng vận tải quy định về việc vận chuyển h&agrave;ng kh&ocirc;ng v&agrave; hoạt động h&agrave;ng kh&ocirc;ng chung</p>\n\n<p>&ndash; Th&ocirc;ng tư số 14/2015/TT-BGTVT ng&agrave;y 27/4/2015 của Bộ Giao th&ocirc;ng vận tải quy định về việc bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại trong vận chuyển h&agrave;nh kh&aacute;ch bằng đường h&agrave;ng kh&ocirc;ng</p>\n\n<p>&ndash; Th&ocirc;ng tư 21/2020/TT-BGTVT ngày 28/09/2020 Sửa đổi, bổ sung một số điều của Th&ocirc;ng tư số 81/2014/TT-BGTVT ng&agrave;y 30 th&aacute;ng 12 năm 2014 của Bộ trưởng Bộ Giao th&ocirc;ng vận tải quy định về việc vận chuyển h&agrave;ng kh&ocirc;ng v&agrave; hoạt động h&agrave;ng kh&ocirc;ng chung, Th&ocirc;ng tư số 14/2015/TT-BGTVT ng&agrave;y 27 th&aacute;ng 4 năm 2015 của Bộ trưởng Bộ Giao th&ocirc;ng vận tải quy định về việc bồi thường ứng trước kh&ocirc;ng ho&agrave;n lại trong vận chuyển h&agrave;nh kh&aacute;ch bằng đường h&agrave;ng kh&ocirc;ng v&agrave; Th&ocirc;ng tư số 33/2016/TT-BGTVT ng&agrave;y 15 th&aacute;ng 11 năm 2016 của Bộ trưởng Bộ Giao th&ocirc;ng vận tải quy định về việc b&aacute;o c&aacute;o hoạt động v&agrave; b&aacute;o c&aacute;o số liệu trong ng&agrave;nh h&agrave;ng kh&ocirc;ng d&acirc;n dụng Việt Nam.</p>\n\n<p>&ndash; Quy định EC261/2004 ng&agrave;y 11/02/2004 quy định chung về bồi thường v&agrave; trợ gi&uacute;p h&agrave;nh kh&aacute;ch trong trường hợp từ chối vận chuyển, hủy chuyến.</p>\n\n<p>&ndash; Điều lệ vận chuyển của Hãng hàng kh&ocirc;ng Datacom.</p>\n',
          Image: '/images/content/DC10899/tukq4rz2.png',
          Highlight: false,
          Position: 0,
          View: 0,
          DayNum: 0,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-05-28T16:39:43.107',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: '0CA3DD14-6F1F-4EF4-810D-2D4D82E0B5F2',
          Index: 327,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'EE626B9F-D336-4410-89A9-2C2E55307630',
          Language: 'vi',
          Alias: 'dieu-kien-va-dieu-khoan',
          Title: 'Điều kiện và điều khoản',
          Intro: null,
          Html: '<p>Điều khoản sử dụng website</p>\n\n<p>Website n&agrave;y thuộc quyền sở hữu v&agrave; quản l&yacute; của C&ocirc;ng ty cổ phần Datacom. Khi truy cập, sử dụng website n&agrave;y, qu&yacute; kh&aacute;ch đ&atilde; mặc nhi&ecirc;n đồng &yacute; với c&aacute;c điều khoản v&agrave; điều kiện đề ra ở đ&acirc;y. Do vậy đề nghị qu&yacute; kh&aacute;ch đọc v&agrave; nghi&ecirc;n cứu kỹ trước khi sử dụng.</p>\n\n<p>&nbsp;</p>\n\n<p>1. Chấp thuận c&aacute;c Điều kiện Sử dụng</p>\n\n<p>Khi sử dụng website Thương mại Điện tử của Datacom (sau đ&acirc;y gọi tắt l&agrave; &ldquo;Website&rdquo;), qu&yacute; kh&aacute;ch đ&atilde; mặc nhi&ecirc;n chấp thuận c&aacute;c điều khoản v&agrave; điều kiện sử dụng (sau đ&acirc;y gọi tắt l&agrave; &ldquo;Điều kiện Sử dụng&rdquo;) được quy định dưới đ&acirc;y. Để biết được c&aacute;c sửa đổi mới nhất, qu&yacute; kh&aacute;ch n&ecirc;n thường xuy&ecirc;n kiểm tra lại &ldquo;Điều kiện Sử dụng&rdquo;. Datacom c&oacute; quyền thay đổi, điều chỉnh, th&ecirc;m hay bớt c&aacute;c nội dung của &ldquo;Điều kiện Sử dụng&rdquo; tại bất kỳ thời điểm n&agrave;o. Nếu qu&yacute; kh&aacute;ch vẫn tiếp tục sử dụng website sau khi c&oacute; c&aacute;c thay đổi như vậy th&igrave; c&oacute; nghĩa l&agrave; qu&yacute; kh&aacute;ch đ&atilde; chấp thuận c&aacute;c thay đổi đ&oacute;.</p>\n\n<p>2. T&iacute;nh chất của th&ocirc;ng tin hiển thị</p>\n\n<p>C&aacute;c nội dung hiển thị tr&ecirc;n Website nhằm mục đ&iacute;ch cung cấp th&ocirc;ng tin về Datacom, về chương tr&igrave;nh kh&aacute;ch h&agrave;ng th&acirc;n th&iacute;ch Bamboo Club, về dịch vụ vận chuyển h&agrave;nh kh&aacute;ch, h&agrave;nh l&yacute; v&agrave; h&agrave;ng h&oacute;a của h&atilde;ng, dịch vụ kh&aacute;ch sạn, cũng như c&aacute;c dịch vụ bổ trợ kh&aacute;c li&ecirc;n quan đến du lịch, lữ h&agrave;nh của nhiều nh&agrave; cung cấp kh&aacute;c nhau (sau đ&acirc;y được gọi chung l&agrave; &ldquo;Nh&agrave; Cung cấp&rdquo;).</p>\n\n<p>3. Li&ecirc;n kết đến Website kh&aacute;c</p>\n\n<p>Website cung cấp một số li&ecirc;n kết tới trang web hoặc nguồn dữ liệu kh&aacute;c. Qu&yacute; kh&aacute;ch tự chịu tr&aacute;ch nhiệm khi sử dụng c&aacute;c li&ecirc;n kết n&agrave;y. Datacom kh&ocirc;ng tiến h&agrave;nh thẩm định hay x&aacute;c thực nội dung, t&iacute;nh ch&iacute;nh x&aacute;c, quan điểm thể hiện tại c&aacute;c trang web v&agrave; nguồn dữ liệu li&ecirc;n kết n&agrave;y. Datacom từ chối bất cứ tr&aacute;ch nhiệm ph&aacute;p l&yacute; n&agrave;o li&ecirc;n quan tới t&iacute;nh ch&iacute;nh x&aacute;c, nội dung thể hiện, mức độ an to&agrave;n v&agrave; việc cho hiển thị hay che đi c&aacute;c th&ocirc;ng tin tr&ecirc;n c&aacute;c trang web v&agrave; nguồn dữ liệu n&oacute;i tr&ecirc;n.</p>\n\n<p>4. Li&ecirc;n kết từ Website kh&aacute;c</p>\n\n<p>Datacom kh&ocirc;ng cho ph&eacute;p bất kỳ nh&agrave; cung cấp dịch vụ internet n&agrave;o được ph&eacute;p &ldquo;đặt to&agrave;n bộ&rdquo; hay &ldquo;nh&uacute;ng&rdquo; bất kỳ th&agrave;nh tố n&agrave;o của Website n&agrave;y sang một trang kh&aacute;c hoặc sử dụng c&aacute;c kỹ thuật l&agrave;m thay đổi giao diện/ hiển thị mặc định của Website.</p>\n\n<p>5. Miễn trừ tr&aacute;ch nhiệm</p>\n\n<p>Th&ocirc;ng tin hiển thị tại website n&agrave;y kh&ocirc;ng đi k&egrave;m bất kỳ đảm bảo hay cam kết tr&aacute;ch nhiệm dưới bất kỳ h&igrave;nh thức n&agrave;o từ ph&iacute;a Datacom hay nh&agrave; cung cấp kh&aacute;c, ch&iacute;nh thức hay h&agrave;m &yacute;, bao gồm nhưng kh&ocirc;ng giới hạn về sự ph&ugrave; hợp của sản phẩm, dịch vụ m&agrave; người mua đ&atilde; lựa chọn.</p>\n\n<p>Datacom v&agrave; c&aacute;c nh&agrave; cung cấp kh&aacute;c cũng từ chối tr&aacute;ch nhiệm hay đưa ra đảm bảo rằng website sẽ kh&ocirc;ng c&oacute; lỗi vận h&agrave;nh, an to&agrave;n, kh&ocirc;ng bị gi&aacute;n đoạn hay bất cứ đảm bảo n&agrave;o về t&iacute;nh ch&iacute;nh x&aacute;c, đầy đủ v&agrave; đ&uacute;ng hạn của c&aacute;c th&ocirc;ng tin hiển thị.</p>\n\n<p>Khi truy cập v&agrave;o website n&agrave;y, qu&yacute; kh&aacute;ch mặc nhi&ecirc;n đồng &yacute; rằng Datacom, c&aacute;c nh&agrave; cung cấp kh&aacute;c c&ugrave;ng với đối t&aacute;c li&ecirc;n kết, nh&acirc;n vi&ecirc;n, c&aacute;n bộ quản l&yacute; v&agrave; người đại diện của họ kh&ocirc;ng chịu bất cứ tr&aacute;ch nhiệm n&agrave;o li&ecirc;n quan đến thương tật, mất m&aacute;t, khiếu kiện, thiệt hại trực tiếp hoặc thiệt hại gi&aacute;n tiếp do kh&ocirc;ng lường trước hoặc do hậu quả để lại dưới bất kỳ h&igrave;nh thức n&agrave;o ph&aacute;t sinh từ hay c&oacute; li&ecirc;n quan đến việc:</p>\n\n<p>(1) Sử dụng c&aacute;c th&ocirc;ng tin tr&ecirc;n website n&agrave;y;</p>\n\n<p>(2) C&aacute;c truy cập kết nối từ website n&agrave;y;</p>\n\n<p>(3) Đăng k&yacute; th&agrave;nh vi&ecirc;n, đăng k&yacute; nhận thư điện tử hay tham gia v&agrave;o chương tr&igrave;nh kh&aacute;ch h&agrave;ng th&acirc;n thiết của Datacom;</p>\n\n<p>(4) Datacom hay một nh&agrave; cung cấp n&agrave;o đ&oacute; c&oacute; thực hiện việc cung cấp dịch vụ hay kh&ocirc;ng thậm ch&iacute; trong trường hợp Datacom hay nh&agrave; cung cấp đ&oacute; đ&atilde; được cảnh b&aacute;o về khả năng xẩy ra thiệt hại;</p>\n\n<p>(5) C&aacute;c hạn chế li&ecirc;n quan đến đặt chỗ trực tuyến m&ocirc; tả tại đ&acirc;y.</p>\n\n<p>C&aacute;c điều kiện v&agrave; hạn chế n&ecirc;u tr&ecirc;n chỉ c&oacute; hiệu lực trong khu&ocirc;n khổ ph&aacute;p luật hiện h&agrave;nh.</p>\n\n<p>6. Quyền sở hữu tr&iacute; tuệ</p>\n\n<p>Website n&agrave;y v&agrave; mọi nội dung xếp đặt, hiển thị đều thuộc sở hữu v&agrave; l&agrave; t&agrave;i sản độc quyền khai th&aacute;c của Datacom v&agrave; c&aacute;c nh&agrave; cung cấp c&oacute; li&ecirc;n quan kh&aacute;c. Mọi sử dụng, tr&iacute;ch dẫn phải kh&ocirc;ng g&acirc;y thiệt hại cho Datacom v&agrave; đều phải tu&acirc;n thủ c&aacute;c điều kiện sau: (1) Chỉ sử dụng cho mục đ&iacute;ch c&aacute; nh&acirc;n, phi thương mại; (2) c&aacute;c sao ch&eacute;p hoặc tr&iacute;ch dẫn đều phải giữ nguy&ecirc;n dấu hiệu bản quyền hoặc c&aacute;c yết thị về quyền sở hữu tr&iacute; tuệ như đ&atilde; thể hiện trong phi&ecirc;n bản gốc; v&agrave; (3) mọi sản phẩm, c&ocirc;ng nghệ hay quy tr&igrave;nh được sử dụng hay hiển thị tại Website n&agrave;y đều c&oacute; thể li&ecirc;n đới đến bản quyền hay sở hữu tr&iacute; tuệ kh&aacute;c của Datacom v&agrave; c&aacute;c nh&agrave; cung cấp c&oacute; li&ecirc;n quan m&agrave; kh&ocirc;ng thể chuyển nhượng được. Tất cả c&aacute;c nội dung được cung cấp tại Website n&agrave;y kh&ocirc;ng được ph&eacute;p nh&acirc;n bản, hiển thị, c&ocirc;ng bố, phổ biến, đưa tin tức hay lưu h&agrave;nh cho bất cứ ai, dưới bất kỳ h&igrave;nh thức n&agrave;o, kể cả tr&ecirc;n c&aacute;c Website độc lập kh&aacute;c m&agrave; kh&ocirc;ng được sự chấp thuận của Datacom. Mọi h&igrave;nh ảnh, thương hiệu, nh&atilde;n hiệu hay biểu tượng tr&igrave;nh b&agrave;y tại Website n&agrave;y được bảo vệ bởi Luật sở hữu tr&iacute; tuệ v&agrave; c&aacute;c điều luật c&oacute; li&ecirc;n quan kh&aacute;c v&agrave; việc qu&yacute; kh&aacute;ch sử dụng Website n&agrave;y kh&ocirc;ng cho ph&eacute;p qu&yacute; kh&aacute;ch được quyền sử dụng, nh&acirc;n bản hay sở hữu.</p>\n\n<p>7. Điều chỉnh v&agrave; sửa đổi</p>\n\n<p>Datacom bảo lưu quyền thay đổi, chỉnh sửa hoặc chấm dứt hoạt động của Website n&agrave;y v&agrave;o bất cứ thời điểm n&agrave;o.</p>\n\n<p>8. Luật điều chỉnh v&agrave; cơ quan giải quyết tranh chấp</p>\n\n<p>Điều kiện Sử dụng n&agrave;y được điều chỉnh bởi luật của nước Cộng ho&agrave; X&atilde; hội Chủ nghĩa Việt Nam. T&ograve;a &aacute;n nước Cộng h&ograve;a X&atilde; hội Chủ nghĩa Việt Nam l&agrave; cơ quan duy nhất c&oacute; thẩm quyền giải quyết tất cả c&aacute;c tranh chấp c&oacute; li&ecirc;n quan.</p>\n',
          Image: '/images/content/DC10899/ldkyzlsk.png',
          Highlight: false,
          Position: 0,
          View: 0,
          DayNum: 0,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-05-28T16:36:59.767',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: '28C9324C-C06C-493A-A282-2A0DA895F752',
          Index: 326,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'EE626B9F-D336-4410-89A9-2C2E55307630',
          Language: 'vi',
          Alias: 'huong-dan-dang-ky',
          Title: 'Hướng dẫn đăng ký',
          Intro: null,
          Html: '<h2>Tham khảo chi tiết hướng dẫn:</h2>\n\n<p><strong>Bước 1</strong>: Truy cập v&agrave;o trang chủ của Bamboo Airways tại:&nbsp;<a href="http://www.bambooairways.com/" target="_blank">www.bambooairways.com</a>&nbsp;v&agrave; đăng nhập v&agrave;o t&agrave;i khoản hội vi&ecirc;n.</p>\n\n<p><strong>Bước 2</strong>: Điền đầy đủ th&ocirc;ng tin hội vi&ecirc;n theo y&ecirc;u cầu để đăng nhập v&agrave;o t&agrave;i khoản hội vi&ecirc;n.</p>\n\n<p><strong>Bước 3</strong>: Sau khi đăng nhập, lựa chọn đạt v&eacute; tại mục &ldquo;Bằng Tiền &amp; Điểm&rdquo; v&agrave; lựa chọn h&agrave;nh tr&igrave;nh theo mong muốn. Tiếp theo nhấn &ldquo;T&igrave;m chuyến bay&rdquo; để tiếp tục.</p>\n\n<p><strong>Bước 4</strong>: Hệ thống sẽ hiện l&ecirc;n y&ecirc;u cầu nhập m&atilde; PIN để x&aacute;c nhận sử dụng điểm từ t&agrave;i khoản. Vui l&ograve;ng nhập m&atilde; PIN để x&aacute;c minh v&agrave; tiếp tục.</p>\n\n<p><strong>Lưu &yacute;</strong>: Trong trường hợp qu&ecirc;n m&atilde; PIN, vui l&ograve;ng sử dụng email ch&iacute;nh chủ đ&atilde; đăng k&yacute; hội vi&ecirc;n gửi về mail&nbsp;<a href="mailto:bambooclub@bambooairways.com">bambooclub@bambooairways.com</a>&nbsp;k&egrave;m theo ảnh chụp mặt trước chứng minh nh&acirc;n d&acirc;n hoặc căn cước c&ocirc;ng d&acirc;n, hộ chiếu để được đối chiếu th&ocirc;ng tin v&agrave; hỗ trợ.</p>\n\n<p><strong>Bước 5</strong>: Sau khi chọn h&agrave;nh tr&igrave;nh, lựa chọn loại gi&aacute; mong muốn.</p>\n\n<p><strong>Bước 6</strong>: Sau khi lựa chọn chuyến bay ph&ugrave; hợp, kiểm tra th&ocirc;ng tin h&agrave;nh tr&igrave;nh, v&agrave; tổng số tiền của v&eacute;. Khi th&ocirc;ng tin v&agrave; gi&aacute; v&eacute; đ&atilde; ch&iacute;nh x&aacute;c, qu&yacute; hội vi&ecirc;n k&eacute;o xuống b&ecirc;n dưới để sử dụng thanh k&eacute;o giữa Tiền &amp; Điểm.</p>\n\n<p>Tiếp tục k&eacute;o thanh c&ocirc;ng cụ đến mức điểm quy đổi mong muốn, kiểm tra số điểm sẽ quy đổi, v&agrave; số tiền c&ograve;n lại cần thanh to&aacute;n.</p>\n\n<p>Sau đ&oacute; nhấn, &ldquo;Điền th&ocirc;ng tin h&agrave;nh kh&aacute;ch&rdquo;, để tiếp tục khi đ&atilde; đồng &yacute; với mức điểm đổi, v&agrave; số tiền cần thanh to&aacute;n.</p>\n\n<p>Lưu &yacute;: Số điểm tối đ&atilde; được sử dụng lu&ocirc;n nhỏ hơn số điểm c&oacute; trong t&agrave;i khoản của qu&yacute; hội vi&ecirc;n.</p>\n\n<p><strong>Bước 7</strong>: Th&ocirc;ng tin hội vi&ecirc;n sẽ tự động điền đầy đủ ở c&aacute;c trường th&ocirc;ng tin b&ecirc;n dưới, kiểm tra lại c&aacute;c mục th&ocirc;ng tin c&aacute; nh&acirc;n v&agrave; nhấn &ldquo;X&aacute;c nhận&rdquo;.</p>\n\n<p><strong>Bước 8</strong>: C&oacute; thể lựa chọn th&ecirc;m c&aacute;c dịch vụ bổ trợ như &ldquo;Mua th&ecirc;m h&agrave;nh l&yacute;&rdquo;, &ldquo;Chọn trước chỗ ngồi&rdquo;, &ldquo;Ph&ograve;ng chờ thương gia&rdquo;.</p>\n\n<p><strong>Bước 9</strong>: Nếu c&oacute; lựa chọn th&ecirc;m dịch vụ bổ trợ bất kỳ, c&oacute; thể k&eacute;o thanh c&ocirc;ng cụ Nếu lựa chọn mua v&eacute; bằng Tiền v&agrave; Điểm, hiện tại Bamboo Airways chỉ chấp nhận h&igrave;nh thức thanh to&aacute;n bằng Thẻ T&iacute;n dụng hoặc Ghi nợ Quốc tế.</p>\n\n<p>Sau khi thanh to&aacute;n th&agrave;nh c&ocirc;ng, hệ thống sẽ tự động gửi v&eacute; điện tử về email của hội vi&ecirc;n v&agrave; th&ocirc;ng b&aacute;o x&aacute;c nhận đ&atilde; đặt v&eacute; th&agrave;nh c&ocirc;ng.</p>\n',
          Image: '/images/content/DC10899/55g2uflw.png',
          Highlight: false,
          Position: 0,
          View: 0,
          DayNum: 0,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-05-28T16:34:13.39',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: 'EB429D21-37AB-4157-830E-61B5DD249155',
          Index: 325,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'EE626B9F-D336-4410-89A9-2C2E55307630',
          Language: 'vi',
          Alias: 'gioi-thieu',
          Title: 'Giới thiệu',
          Intro: null,
          Html: '<p><em>Từ một doanh nghiệp lữ h&agrave;nh được th&agrave;nh lập với mục ti&ecirc;u ph&aacute;t triển th&agrave;nh thương hiệu du lịch vượt trội, chất lượng cao, đạt ti&ecirc;u chuẩn quốc tế v&agrave; ph&ugrave; hợp với y&ecirc;u cầu ph&aacute;t triển của ng&agrave;nh du lịch Việt Nam. Ch&uacute;ng t&ocirc;i kh&ocirc;ng ngừng củng cố hệ thống dịch vụ v&agrave; ho&agrave;n thiện sản phẩm du lịch của m&igrave;nh để l&agrave;m h&agrave;i l&ograve;ng mọi kh&aacute;ch h&agrave;ng.&nbsp;</em></p>\n\n<h4>C&Acirc;U CHUYỆN CỦA CH&Uacute;NG T&Ocirc;I</h4>\n\n<p>Du lịch kh&ocirc;ng đơn thuần l&agrave; việc di chuyển từ một địa điểm n&agrave;y đến địa điểm kh&aacute;c, m&agrave; c&ograve;n l&agrave; cơ hội để kh&aacute;m ph&aacute; văn h&oacute;a, thi&ecirc;n nhi&ecirc;n v&agrave; con người tr&ecirc;n khắp thế giới. Từ những t&acirc;m hồn đam m&ecirc; du lịch v&agrave; ước mơ gi&uacute;p mọi du kh&aacute;ch c&oacute; nhiều trải nghiệm th&uacute; vị, đ&aacute;ng nhớ khi kh&aacute;m ph&aacute; thế giới; ch&uacute;ng t&ocirc;i đ&atilde; cho ra đời C&ocirc;ng ty Lữ h&agrave;nh quốc tế Thi&ecirc;n Minh (viết tắt l&agrave; Thi&ecirc;n Minh Travel hoặc Thi&ecirc;n Minh) v&agrave;o ng&agrave;y 04/12/2013. Thi&ecirc;n Minh Travel chuy&ecirc;n cung cấp c&aacute;c dịch vụ v&eacute; m&aacute;y bay, xe du lịch, visa, tour trọn g&oacute;i&hellip;. Trong suốt gần 10 năm x&acirc;y dựng, ch&uacute;ng t&ocirc;i đ&atilde; nhận được sự đ&aacute;nh gi&aacute; cao từ hơn 200 đối t&aacute;c v&agrave; h&agrave;ng ng&agrave;n du kh&aacute;ch. Đ&acirc;y l&agrave; động lực để ch&uacute;ng t&ocirc;i vững tin ph&aacute;t triển một thương hiệu mang tầm quốc tế v&agrave; c&oacute; uy t&iacute;n trong lĩnh vực du lịch.&nbsp;&nbsp; &nbsp;</p>\n\n<p>Với bề d&agrave;y h&igrave;nh th&agrave;nh v&agrave; ph&aacute;t triển gần 10 năm trong lĩnh vực h&agrave;ng kh&ocirc;ng, vận chuyển &amp; du lịch cũng như để ph&ugrave; hợp với c&aacute;c định hướng vươn tầm quốc tế trong tương lai; ng&agrave;y 14 th&aacute;ng 04 năm 2022, C&ocirc;ng ty Lữ h&agrave;nh quốc tế Thi&ecirc;n Minh quyết định đổi t&ecirc;n thương hiệu th&agrave;nh <strong>C&ocirc;ng ty TNHH Datacom</strong> (viết tắt l&agrave; <strong>Datacom</strong>).</p>\n\n<p><img src="https://resources.datacom.vn/data/content/images/rarmk41h.jpg" /></p>\n\n<p>Kế thừa v&agrave; ph&aacute;t huy hiệu quả c&aacute;c gi&aacute; trị cốt l&otilde;i của C&ocirc;ng ty Lữ h&agrave;nh quốc tế Thi&ecirc;n Minh, Datacom đang kh&ocirc;ng ngừng cố gắng v&agrave; hình thành l&ecirc;n m&ocirc;̣t đ&ocirc;̣i ngũ nh&acirc;n vi&ecirc;n trẻ, năng đ&ocirc;̣ng, c&oacute; t&acirc;m với nghề để tự m&igrave;nh vươn l&ecirc;n, hướng tới mục ti&ecirc;u hoạt động đa ng&agrave;nh theo luật doanh nghiệp v&agrave; c&aacute;c quy định hiện h&agrave;nh của luật ph&aacute;p Việt Nam.&nbsp;</p>\n\n<p>Datacom cũng kh&ocirc;ng ngừng mở rộng phạm vi hoạt động của m&igrave;nh, đặc biệt l&agrave; trong lĩnh vực li&ecirc;n quan đến hoạt động b&aacute;n v&eacute; m&aacute;y bay. Với phương ch&acirc;m hướng đến sự h&agrave;i l&ograve;ng trọn vẹn của kh&aacute;ch h&agrave;ng, Datacom đặt mục ti&ecirc;u trở th&agrave;nh một trong những thương hiệu uy t&iacute;n h&agrave;ng đầu trong lĩnh vực Du lịch &ndash; H&agrave;ng kh&ocirc;ng cho kh&ocirc;ng chỉ kh&aacute;ch h&agrave;ng tại Việt Nam m&agrave; c&ograve;n cho cả cộng đồng người Việt đang sinh sống tr&ecirc;n khắp thế giới.</p>\n\n<h4>VĂN HO&Aacute; DOANH NGHIỆP</h4>\n\n<p>Nếu hiểu một c&aacute;ch đơn giản th&igrave; &ldquo;Datacom&rdquo; c&oacute; nghĩa l&agrave; mọi h&agrave;nh tr&igrave;nh m&agrave; bất cứ ai tham gia đều tr&agrave;n đầy nụ cười vui vẻ v&agrave; hạnh ph&uacute;c. Tuy nhi&ecirc;n, khi giải nghĩa s&acirc;u xa hơn, mỗi k&yacute; tự trong t&ecirc;n đều l&agrave; gi&aacute; trị v&agrave; th&ocirc;ng điệp &yacute; nghĩa m&agrave; mọi nh&acirc;n vi&ecirc;n của Datacom lu&ocirc;n hướng tới v&agrave; muốn gửi đến kh&aacute;ch h&agrave;ng của m&igrave;nh:</p>\n\n<p><strong>S = Simple: Sự đơn giản</strong>: Phương ch&acirc;m h&agrave;ng đầu của Datacom l&agrave; hướng đến sự đơn giản, kh&ocirc;ng cầu kỳ để kh&aacute;ch h&agrave;ng c&oacute; những trải nghiệm thật tiện lợi v&agrave; nhanh ch&oacute;ng. Ch&uacute;ng t&ocirc;i cũng gửi gắm trong đ&oacute; th&ocirc;ng điệp về một cuộc sống dễ d&agrave;ng, bởi khi c&oacute; Datacom mọi chuyến đi sẽ trở n&ecirc;n v&ocirc; c&ugrave;ng đơn giản.&nbsp;</p>\n\n<p><strong>M = Memorable: Ấn tượng v&agrave; kh&aacute;c biệt</strong>: Ch&uacute;ng t&ocirc;i lu&ocirc;n cố gắng tạo ra những dịch vụ kh&aacute;c biệt, những h&agrave;nh tr&igrave;nh ấn tượng để ghi dấu trong l&ograve;ng kh&aacute;ch h&agrave;ng những kỷ niệm v&agrave; khoảnh khắc đ&aacute;ng nhớ sau mỗi chuyến đi.&nbsp;</p>\n\n<p><strong>I = Interesting</strong>: Datacom lu&ocirc;n kh&ocirc;ng ngừng đổi mới, kh&aacute;m ph&aacute;, học hỏi để t&igrave;m ra những địa điểm, văn h&oacute;a, hoặc hoạt động mới mẻ gi&uacute;p h&agrave;nh tr&igrave;nh trải nghiệm của kh&aacute;ch h&agrave;ng lu&ocirc;n thật th&uacute; vị.</p>\n\n<p><strong>L = Leader</strong>: Mỗi nh&acirc;n vi&ecirc;n trong c&ocirc;ng ty TNHH Datacom sẽ l&agrave; 1 người L&atilde;nh Đạo qua ch&iacute;nh h&agrave;nh động của m&igrave;nh với C&ocirc;ng ty dựa v&agrave;o tr&aacute;ch nhiệm v&agrave; những quyết định s&aacute;ng suốt.</p>\n\n<p><strong>E - Emotion</strong>: Cảm x&uacute;c t&iacute;ch cực lu&ocirc;n l&agrave; điều quan trọng nhất m&agrave; ch&uacute;ng t&ocirc;i muốn tạo ra cho kh&aacute;ch h&agrave;ng v&agrave; mọi nh&acirc;n vi&ecirc;n trong c&ocirc;ng ty. Với Datacom, EQ sẽ lu&ocirc;n được đề cao &amp; đ&aacute;nh gi&aacute; mạnh hơn IQ trong ng&agrave;nh dịch vụ du &nbsp;lịch.</p>\n\n<p><img src="https://resources.datacom.vn/data/content/images/zsrl0xlu.jpg" /></p>\n\n<h4>&nbsp;</h4>\n\n<h4>TẦM NH&Igrave;N, SỨ MỆNH V&Agrave; GI&Aacute; TRỊ CỐT L&Otilde;I</h4>\n\n<h4>Tầm Nh&igrave;n:</h4>\n\n<p>Datacom định hướng ph&aacute;t triển th&agrave;nh một trong những c&ocirc;ng ty du lịch v&agrave; đại l&yacute; b&aacute;n v&eacute; m&aacute;y bay c&oacute; chất lượng dịch vụ tốt nhất d&agrave;nh cho cộng động người Việt tr&ecirc;n khắp thế giới. Năm 2025, Smile Trip sẽ cho ra mắt website đặt v&eacute; m&aacute;y bay trực tuyến d&agrave;nh ri&ecirc;ng cho người Việt tại nước ngo&agrave;i với mức gi&aacute; tốt nhất thị trường.</p>\n\n<h4>Sứ Mệnh:</h4>\n\n<p>Datacom lu&ocirc;n cố gắng đưa ra mức gi&aacute; hợp l&yacute; để gi&uacute;p qu&yacute; kh&aacute;ch tiết kiệm tối đa chi ph&iacute; khi mua v&eacute; m&aacute;y bay, đồng thời kh&ocirc;ng ngừng n&acirc;ng cao chất lượng phục vụ với mục ti&ecirc;u mỗi h&agrave;nh tr&igrave;nh l&agrave; một c&acirc;u chuyện đ&aacute;ng nhớ để kh&aacute;ch h&agrave;ng cảm nhận sự kh&aacute;c biệt ngay từ lần đầu ti&ecirc;n sử dụng dịch vụ.</p>\n\n<h4>Gi&aacute; trị cốt l&otilde;i:&nbsp;</h4>\n\n<p>Những gi&aacute; trị cốt l&otilde;i l&agrave; lời cam kết của Datacom đối với kh&aacute;ch h&agrave;ng, đối t&aacute;c, với x&atilde; hội v&agrave; với ch&iacute;nh bản th&acirc;n ch&uacute;ng t&ocirc;i. Những gi&aacute; trị n&agrave;y l&agrave; kim chỉ nam cho mọi hoạt động của C&ocirc;ng ty để trở th&agrave;nh một doanh nghiệp kh&ocirc;ng ngừng ph&aacute;t triển v&igrave; chất lượng cuộc sống:</p>\n\n<ul>\n\t<li>Tận t&acirc;m với Kh&aacute;ch h&agrave;ng, kh&ocirc;ng ngừng n&acirc;ng cao chất lượng dịch vụ</li>\n\t<li>L&agrave;m đ&uacute;ng cam kết v&agrave; sẵn s&agrave;ng nhận tr&aacute;ch nhiệm</li>\n\t<li>Đồng l&ograve;ng &ndash; hỗ trợ &ndash; tin tưởng đồng nghiệp</li>\n\t<li>Hướng tới cộng đồng.</li>\n</ul>\n\n<h4><img src="https://resources.datacom.vn/data/content/images/tedmlhio.jpg" /></h4>\n\n<h4>&nbsp;</h4>\n\n<h4>CHẶNG ĐƯỜNG PH&Aacute;T TRIỂN&nbsp;</h4>\n\n<p>C&ocirc;ng ty Lữ h&agrave;nh quốc tế Thi&ecirc;n Minh th&agrave;nh lập v&agrave;o ng&agrave;y 04/12/2013. Từ những bước ch&acirc;n chập chững ban đầu C&ocirc;ng ty đ&atilde; trải qua v&ocirc; v&agrave;n kh&oacute; khăn th&aacute;ch thức nhưng sự đam m&ecirc;, nỗ lực v&agrave; cố gắng kh&ocirc;ng ngừng nghỉ của tất cả nh&acirc;n vi&ecirc;n đ&atilde; biến mọi mơ ước th&agrave;nh hiện thực.</p>\n\n<p>V&agrave;o ng&agrave;y 11/10/2018, Thi&ecirc;n Minh Travel đ&atilde; mở rộng tầm nh&igrave;n v&agrave; bước ch&acirc;n ra thị trường quốc tế bằng việc th&agrave;nh lập Chi nh&aacute;nh tại Osaka, Nhật Bản. Điều n&agrave;y kh&ocirc;ng chỉ thể hiện sự tự tin v&agrave; quyết t&acirc;m của c&ocirc;ng ty, m&agrave; c&ograve;n tạo nền tảng cho việc khẳng định danh tiếng tr&ecirc;n bản đồ du lịch quốc tế.</p>\n\n<p>Ng&agrave;y 14/04/2022 đ&aacute;nh dấu bước ngoặt quan trọng trong h&agrave;nh tr&igrave;nh của Thi&ecirc;n Minh Travel khi quyết định đổi t&ecirc;n thương hiệu th&agrave;nh Datacom. Thương hiệu mới mang theo một th&ocirc;ng điệp tươi mới, ngập tr&agrave;n niềm vui v&agrave; sự phấn kh&iacute;ch, thể hiện cam kết kh&ocirc;ng ngừng cải tiến v&agrave; mang lại những trải nghiệm du lịch đ&aacute;ng nhớ cho kh&aacute;ch h&agrave;ng.</p>\n\n<p>Đến ng&agrave;y 03/09/2023, Datacom tiếp tục mở rộng khu vực kinh doanh với việc th&agrave;nh lập Chi nh&aacute;nh tại Paris, Ph&aacute;p. Điều n&agrave;y kh&ocirc;ng chỉ tạo cơ hội cho việc kh&aacute;m ph&aacute; một trong những điểm du lịch hấp dẫn tr&ecirc;n thế giới m&agrave; c&ograve;n chứng minh sự đam m&ecirc; v&agrave; tầm nh&igrave;n to&agrave;n cầu của Datacom.</p>\n\n<p><img src="https://resources.datacom.vn/data/content/images/fr1xbjh2.jpg" /></p>\n\n<p>Chặng đường ph&aacute;t triển của Datacom l&agrave; một c&acirc;u chuyện về sự ki&ecirc;n tr&igrave;, s&aacute;ng tạo v&agrave; quyết t&acirc;m vươn l&ecirc;n vượt qua mọi kh&oacute; khăn. Với tầm nh&igrave;n, nỗ lực v&agrave; cam kết của m&igrave;nh, Datacom đang x&acirc;y dựng một h&agrave;nh tr&igrave;nh đầy hứa hẹn, đưa mọi điểm đến tươi đẹp tr&ecirc;n thế giới đến thật gần với mọi du kh&aacute;ch.</p>\n\n<ul>\n\t<li>C&ocirc;ng ty Thi&ecirc;n Minh Travel th&agrave;nh lập ng&agrave;y 04/12/2013 tại Việt Nam</li>\n\t<li>Ng&agrave;y 14/10/2018 th&agrave;nh lập Thi&ecirc;n Minh travel tại Osaka</li>\n\t<li>Ng&agrave;y 14/04/2022 Thi&ecirc;n Minh Travel đổi t&ecirc;n th&agrave;nh Smile Trip</li>\n\t<li>Ng&agrave;y 03/09/2023 th&agrave;nh lập Smile Trip tại Paris.</li>\n</ul>\n\n<h4>CHỨNG CHỈ</h4>\n\n<p>Thấu hiểu mong muốn của kh&aacute;ch h&agrave;ng cũng như cam kết lu&ocirc;n l&agrave;m điều tốt nhất cho mọi dự &aacute;n hợp t&aacute;c, Datacom đang ng&agrave;y c&agrave;ng c&oacute; được sự tin tưởng v&agrave; phản hồi rất t&iacute;ch cực từ đối t&aacute;c khi trở th&agrave;nh đại l&yacute; cấp 1 của nhiều h&atilde;ng h&agrave;ng kh&ocirc;ng trong v&agrave; ngo&agrave;i nước:</p>\n\n<ul>\n\t<li>Đại l&yacute; chỉ định của Hiệp Hội Vận Tải H&agrave;ng Kh&ocirc;ng Quốc Tế (IATA) (cấp cho Thien Minh Travel tại Nhật Bản)</li>\n\t<li>Đại l&yacute; ph&acirc;n phối ch&iacute;nh thức của Vietnam Airlines tại Nhật Bản (Thien Minh Travel tại Nhật Bản)</li>\n\t<li>Đại l&yacute; ch&iacute;nh thức của Vietnam Airlines tại Việt Nam</li>\n\t<li>Đại l&yacute; ch&iacute;nh thức của Bamboo Airways tại Nhật Bản v&agrave; Việt Nam</li>\n\t<li>Đại l&yacute; ch&iacute;nh thức của Vietjet Air tại Nhật Bản v&agrave; Việt Nam.</li>\n</ul>\n\n<h4>SẢN PHẨM NỔI BẬT</h4>\n\n<p>Datacom tự h&agrave;o giới thiệu những sản phẩm v&agrave; dịch vụ nổi bật, tạo n&ecirc;n sự kh&aacute;c biệt v&agrave; đ&aacute;p ứng đa dạng nhu cầu của du kh&aacute;ch:</p>\n\n<ul>\n\t<li>V&eacute; m&aacute;y bay gi&aacute; cạnh tranh d&agrave;nh cho cộng đồng người Việt tại Nhật Bản</li>\n\t<li>V&eacute; m&aacute;y bay nội địa v&agrave; quốc tế của nhiều h&atilde;ng h&agrave;ng kh&ocirc;ng trong v&agrave; ngo&agrave;i nước, từ h&atilde;ng quốc gia cho đến h&atilde;ng gi&aacute; rẻ (LCC)</li>\n\t<li>Tour du lịch trong v&agrave; ngo&agrave;i nước, đặc biệt cung cấp tour thiết kế ri&ecirc;ng theo nhu cầu của kh&aacute;ch h&agrave;ng</li>\n\t<li>Dịch vụ đưa đ&oacute;n tại s&acirc;n bay Việt Nam v&agrave; Nhật Bản</li>\n\t<li>Dịch vụ tư vấn v&agrave; xin visa.</li>\n</ul>\n\n<h4>KH&Aacute;CH H&Agrave;NG LỚN&nbsp;</h4>\n\n<p>Dưới đ&acirc;y l&agrave; một số trong những kh&aacute;ch h&agrave;ng lớn m&agrave; Datacom vinh dự được phục vụ:</p>\n\n<ul>\n\t<li>FPT Techno Japan</li>\n\t<li>C&ocirc;ng ty TNHH CMC Global</li>\n\t<li>C&ocirc;ng ty TNHH Pacific Hospitality</li>\n\t<li>C&ocirc;ng đo&agrave;n X&acirc;y dựng Việt Nam</li>\n\t<li>C&ocirc;ng ty CP Dịch vụ h&agrave;ng h&oacute;a h&agrave;ng kh&ocirc;ng Việt Nam</li>\n\t<li>C&ocirc;ng ty World Airplane Nhật Bản&hellip;&nbsp;</li>\n</ul>\n\n<p>Ch&uacute;ng t&ocirc;i xem những kh&aacute;ch h&agrave;ng lớn n&agrave;y kh&ocirc;ng chỉ l&agrave; đối t&aacute;c m&agrave; c&ograve;n l&agrave; một phần quan trọng trong chặng đường ph&aacute;t triển của Datacom. Sự t&iacute;n nhiệm v&agrave; hợp t&aacute;c của họ đ&atilde; th&uacute;c đẩy ch&uacute;ng t&ocirc;i phấn đấu kh&ocirc;ng ngừng, mang đến những dịch vụ tốt nhất v&agrave; đ&aacute;p ứng mọi nhu cầu của họ.</p>\n',
          Image: '/images/content/DC10899/asy4paf3.png',
          Highlight: false,
          Position: 0,
          View: 0,
          DayNum: 0,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-05-28T16:16:38.713',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: '8D90ECE1-3B49-412D-91D8-1F3541F8F722',
          Index: 324,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'A07AE577-B273-4C89-905F-3457BCD30D87',
          Language: 'vi',
          Alias:
            'khi-di-may-bay-toi-duoc-mang-theo-bao-nhieu-kg-hanh-ly-xach-tay',
          Title:
            'Khi đi máy bay tôi được mang theo bao nhiêu kg hành lý xách tay?',
          Intro: null,
          Html: '<p>Quy định về h&agrave;nh l&yacute; x&aacute;ch tay khi đi m&aacute;y bay - Hạng v&eacute; Skyboss của VietJet Air bạn sẽ c&oacute; 10kg h&agrave;nh l&yacute; x&aacute;ch tay miễn ph&iacute;. - Hạng v&eacute; Business của Bamboo Airways bạn sẽ c&oacute; 14kg h&agrave;nh l&yacute; x&aacute;ch tay miễn ph&iacute;. C&aacute;c hạng v&eacute; c&ograve;n lại bạn sẽ được mang 7kg h&agrave;nh l&yacute; x&aacute;ch tay miễn ph&iacute; mỗi người. V&agrave; số c&acirc;n n&agrave;y l&agrave; t&iacute;nh ri&ecirc;ng từng người, kh&ocirc;ng được ph&eacute;p gộp chung. Nếu qu&aacute; 7kg bạn phải mua th&ecirc;m h&agrave;nh l&yacute; k&yacute; gửi.</p>\n',
          Image: '/images/content/DC10899/lp5jf1yy.png',
          Highlight: false,
          Position: 0,
          View: 0,
          DayNum: 0,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-05-28T15:54:37.96',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: '9664C3F8-D888-44AD-A6CD-50D31A3A5D9E',
          Index: 323,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'A07AE577-B273-4C89-905F-3457BCD30D87',
          Language: 'vi',
          Alias:
            'toi-co-duoc-mang-theo-thit-tuoi-song-va-hai-san-theo-hanh-ly-len-may-bay-khong',
          Title:
            'Tôi có được mang theo thịt tươi sống và hải sản theo hành lý lên máy bay không?',
          Intro: null,
          Html: '<p>Đối với h&agrave;nh l&yacute; l&agrave; thịt tươi sống v&agrave; hải sản, bạn cần tu&acirc;n thủ quy định của h&atilde;ng h&agrave;ng kh&ocirc;ng</p>\n',
          Image: '/images/content/DC10899/cdwewud2.png',
          Highlight: false,
          Position: 0,
          View: 0,
          DayNum: 0,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-05-28T15:54:11.513',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: '2CF4BD22-18B6-40D3-957B-CE5FE9B3FEA9',
          Index: 322,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'A07AE577-B273-4C89-905F-3457BCD30D87',
          Language: 'vi',
          Alias:
            'em-be-bao-nhieu-tuoi-thi-duoc-di-may-bay-va-can-nhung-giay-to-gi',
          Title:
            'Em bé bao nhiêu tuổi thì được đi máy bay? Và cần những giấy tờ gì?',
          Intro: null,
          Html: '<p>Em b&eacute; từ 14 ng&agrave;y tuổi trở l&ecirc;n l&agrave; c&oacute; thể đi m&aacute;y bay. Giấy tờ cần mang theo để l&agrave;m thủ tục cho em b&eacute;/ trẻ em.</p>\n',
          Image: '/images/content/DC10899/fxchufp0.png',
          Highlight: false,
          Position: 0,
          View: 0,
          DayNum: 0,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-05-28T15:53:34.653',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
      ],
      TotalItem: 27,
      TotalPage: 3,
      PageIndex: 1,
      PageSize: 10,
      HasPreviousPage: true,
      HasNextPage: true,
      OrderBy: 'CreatedDate',
      SortType: 'Desc',
      GetAll: false,
      Filter: [{ Name: 'Highlight', Value: 'false', Contain: false }],
      CustomProperties: null,
      Message: 'Thành công',
      StatusCode: '000',
      Success: true,
      Expired: false,
      Language: 'vi',
    },
  };
}

async function fakeGetListOutStandingPolicy(): Promise<
  AxiosResponse<ContentLst, any>
> {
  await delay(1000);

  return {
    data: {
      List: [
        {
          Id: '290234D3-2248-4473-8950-8856E59F3A8A',
          Index: 311,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: '1CF73E01-8C23-4C31-ABA8-CEBB4FFA9A88',
          Language: 'vi',
          Alias: 'ha-noi-yeu-cau-truong-hoc-khong-thu-tien-giu-cho',
          Title: 'Hà Nội yêu cầu trường học không thu tiền giữ chỗ',
          Intro:
            'Sở Giáo dục và Đào tạo Hà Nội yêu cầu các trường không thu tiền giữ chỗ, trong khi khoản này lên đến 10-20 triệu đồng ở các cơ sở ngoài công lập.',
          Html: '<p>Th&ocirc;ng tin được n&ecirc;u trong th&ocirc;ng b&aacute;o của Sở ng&agrave;y 22/3. Sở cho biết thời gian qua đ&atilde; nhận được nhiều phản &aacute;nh về c&ocirc;ng t&aacute;c tuyển sinh đầu cấp, trong đ&oacute; nhiều trường y&ecirc;u cầu phụ huynh nộp tiền giữ chỗ hoặc thu, giữ hồ sơ của học sinh. Điều n&agrave;y &quot;g&acirc;y bức x&uacute;c cho học sinh, phụ huynh v&agrave; dư luận x&atilde; hội&quot;.</p>\n\n<p>Sở sẽ phối hợp với c&aacute;c đơn vị c&oacute; li&ecirc;n quan, tăng cường thanh tra, kiểm tra, xử l&yacute; nghi&ecirc;m nếu ph&aacute;t hiện vi phạm.</p>\n\n<figure data-size="true" itemprop="associatedMedia image" itemscope="" itemtype="http://schema.org/ImageObject"><img alt="Học sinh lớp 1 Trường tiểu học Thăng Long, quận Ba Đình, Hà Nội tựu trường, tháng 8/2022. Ảnh: Giang Huy" data-ll-status="loaded" data-src="https://i1-vnexpress.vnecdn.net/2024/03/22/HUY-4323-jpeg-5690-1662125780-2152-1711088806.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=0--cJgibHnC_cGd2H1iKkA" intrinsicsize="680x0" itemprop="contentUrl" loading="lazy" src="https://i1-vnexpress.vnecdn.net/2024/03/22/HUY-4323-jpeg-5690-1662125780-2152-1711088806.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=0--cJgibHnC_cGd2H1iKkA" />\n<figcaption itemprop="description">\n<p>Học sinh lớp 1 Trường tiểu học Thăng Long, quận Ba Đ&igrave;nh, H&agrave; Nội tựu trường, th&aacute;ng 8/2022. Ảnh:&nbsp;<em>Giang Huy</em></p>\n</figcaption>\n</figure>\n\n<p>H&agrave; Nội c&oacute; gần 600 trường tư thục, từ mầm non tới THPT. C&aacute;c trường n&agrave;y thường tuyển sinh bằng c&aacute;ch x&eacute;t học bạ hoặc tổ chức thi ri&ecirc;ng.</p>\n\n<p>Ngo&agrave;i học ph&iacute; v&agrave; c&aacute;c khoản thu dự kiến về đồng phục, cơ sở vật chất, dịch vụ b&aacute;n tr&uacute;, xe đưa đ&oacute;n, nhiều trường y&ecirc;u cầu phụ huynh nộp th&ecirc;m ph&iacute; ghi danh, ph&iacute; nhập học nếu tr&uacute;ng tuyển. Mức n&agrave;y thường từ 1,5 triệu đồng trở l&ecirc;n, nhiều trường thu 10-20 triệu đồng.</p>\n\n<p>Khoản n&agrave;y thường được phụ huynh gọi l&agrave; &quot;tiền cọc&quot; hay ph&iacute; giữ chỗ. Nếu học sinh nhập học, trường sẽ khấu trừ v&agrave;o c&aacute;c chi ph&iacute;. C&ograve;n nếu bỏ, t&ugrave;y trường, phụ huynh c&oacute; thể nhận lại hoặc kh&ocirc;ng.</p>\n\n<p>L&atilde;nh đạo một trường tư thục cho biết việc đưa ra y&ecirc;u cầu tiền cọc để hạn chế hồ sơ ảo, đồng thời để c&aacute;c gia đ&igrave;nh c&acirc;n nhắc, c&oacute; tr&aacute;ch nhiệm với lựa chọn của m&igrave;nh.</p>\n\n<figure data-size="true" itemprop="associatedMedia image" itemscope="" itemtype="http://schema.org/ImageObject"><img alt="Biểu phí của một trường tư ở Hà Nội, gồm phí đặt chỗ. Ảnh chụp màn hình" data-ll-status="loaded" data-src="https://i1-vnexpress.vnecdn.net/2024/03/22/650c6d38-fc19-4df9-a2f2-2782e5-8650-8791-1711089877.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=Jl34WZ_I7y73a0KqgKEH-Q" intrinsicsize="680x0" itemprop="contentUrl" loading="lazy" src="https://i1-vnexpress.vnecdn.net/2024/03/22/650c6d38-fc19-4df9-a2f2-2782e5-8650-8791-1711089877.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=Jl34WZ_I7y73a0KqgKEH-Q" />\n<figcaption itemprop="description">\n<p>Biểu ph&iacute; của một trường tư ở H&agrave; Nội, gồm khoản ph&iacute; đặt chỗ.&nbsp;<em>Ảnh chụp m&agrave;n h&igrave;nh</em></p>\n</figcaption>\n</figure>\n\n<p>Khoản tiền ghi danh, giữ chỗ g&acirc;y tranh c&atilde;i nhiều năm qua. L&yacute; do l&agrave; trong c&aacute;c quy định của ng&agrave;nh gi&aacute;o dục kh&ocirc;ng c&oacute; khoản n&agrave;y, song nhiều trường n&oacute;i hoạt động như doanh nghiệp n&ecirc;n được tự thỏa thuận với phụ huynh.</p>\n\n<p>Năm 2018, Sở Gi&aacute;o dục v&agrave; Đ&agrave;o tạo H&agrave; Nội từng y&ecirc;u cầu c&aacute;c trường tư kh&ocirc;ng thu ph&iacute; ghi danh, giữ chỗ, nhưng sau đ&oacute;, việc n&agrave;y lại tiếp diễn.</p>\n',
          Image: '/images/content/DC10899/o4cygk0p.png',
          Highlight: true,
          Position: 0,
          View: 0,
          DayNum: 7,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-03-27T11:00:28.547',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: '5ABF798D-E4F3-4C6F-BCA5-5765CF300EAF',
          Index: 308,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: '1CF73E01-8C23-4C31-ABA8-CEBB4FFA9A88',
          Language: 'vi',
          Alias: 'gia-xang-co-the-tang-them-vao-ngay-mai',
          Title: 'Giá xăng có thể tăng thêm vào ngày mai',
          Intro:
            'Giá xăng trong nước được dự báo tiếp tục tăng vào ngày mai (28/3), trong đó mức tăng dự báo khoảng 450-600 đồng/lít.',
          Html: '<p><img src="https://photo.znews.vn/w960/Uploaded/bfjysesfzyr/2024_03_27/Xang_tang_ky_luc_6.jpg" /></p>\n\n<p>Theo kế hoạch, li&ecirc;n Bộ C&ocirc;ng Thương - T&agrave;i ch&iacute;nh sẽ điều chỉnh gi&aacute; b&aacute;n lẻ&nbsp;<a href="https://znews.vn/tieu-diem/xang-dau.html" title="Tin tức Xăng dầu" topic-id="4064">xăng dầu</a>&nbsp;theo chu kỳ v&agrave;o ng&agrave;y mai (28/3).</p>\n\n<p>L&atilde;nh đạo một doanh nghiệp đầu mối ph&acirc;n phối xăng dầu ph&iacute;a Nam cho biết gần đ&acirc;y, gi&aacute; dầu th&ocirc; c&oacute; xu hướng tiếp tục tăng do lo ngại thiếu hụt nguồn cung. V&igrave; vậy, nhiều khả năng gi&aacute; xăng dầu trong nước c&oacute; thể tăng lần thứ 2 li&ecirc;n tiếp trong kỳ điều h&agrave;nh n&agrave;y.</p>\n\n<p>Cụ thể, gi&aacute; xăng dự kiến tăng khoảng 450-600 đồng/l&iacute;t, trong khi đ&oacute; dầu diesel c&oacute; thể quay đầu giảm khoảng 250-350 đồng/l&iacute;t. Trường hợp li&ecirc;n Bộ C&ocirc;ng Thương - T&agrave;i ch&iacute;nh chi Quỹ b&igrave;nh ổn, gi&aacute; xăng c&oacute; thể tăng &iacute;t hơn.</p>\n\n<p>Tương tự, chủ một doanh nghiệp ph&acirc;n phối xăng dầu tại miền Bắc cũng dự b&aacute;o nhiều khả năng gi&aacute; xăng sẽ biến động tăng tiếp trong kỳ điều h&agrave;nh ng&agrave;y mai, hiện chiết khấu xăng ở nhiều kho đang về mức khoảng 1.000-1.200 đồng/l&iacute;t.</p>\n\n<p>Nếu đ&uacute;ng như dự b&aacute;o, gi&aacute; xăng trong nước sẽ tăng lần thứ 2 li&ecirc;n tiếp. Từ đầu năm đến nay, gi&aacute; nhi&ecirc;n liệu n&agrave;y đ&atilde; c&oacute; 7 lần tăng v&agrave; 5 lần giảm.</p>\n',
          Image: '/images/content/DC10899/pliusipa.png',
          Highlight: true,
          Position: 0,
          View: 0,
          DayNum: 7,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-03-27T10:57:15.383',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: '92724209-42A7-4E8A-990F-476510587BC4',
          Index: 307,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'FB873680-7553-4E36-84A7-9143DC578CC7',
          Language: 'vi',
          Alias: 'xo-so-tp-hcm-muon-thu-120-ty-dong-moi-ky-quay',
          Title: 'Xổ số TP.HCM muốn thu 120 tỷ đồng mỗi kỳ quay',
          Intro:
            'Công ty xổ số đầu ngành khu vực phía Nam lên kế hoạch có 105 kỳ xổ trong năm nay, không tính các kỳ vé xuân. Ước tính doanh thu bán vé mỗi kỳ thu về 120 tỷ đồng.',
          Html: '<p><img src="https://photo.znews.vn/w960/Uploaded/rohuoct/2022_08_07/ve_so.jpg" /></p>\n\n<p>C&ocirc;ng ty TNHH MTV Xổ số kiến thiết TP.HCM vừa c&ocirc;ng bố kế hoạch kinh doanh năm 2024 với c&aacute;c chỉ ti&ecirc;u đều cao hơn năm 2023.</p>\n\n<p>Cụ thể, c&ocirc;ng ty ước t&iacute;nh tổng doanh thu đạt&nbsp;<abbr>13.683 tỷ đồng</abbr>, tăng nhẹ 1,4% so với thực hiện năm 2023. Trong đ&oacute;, doanh thu xổ số truyền thống tăng&nbsp;<abbr>66 tỷ đồng</abbr>&nbsp;l&ecirc;n&nbsp;<abbr>12.571 tỷ đồng</abbr>, c&ograve;n doanh thu xổ số c&agrave;o đạt&nbsp;<abbr>720 tỷ đồng</abbr>, tăng&nbsp;<abbr>151 tỷ đồng</abbr>.</p>\n\n<p>Với chỉ ti&ecirc;u lợi nhuận trước thuế, Xổ số TP.HCM dự kiến năm nay tăng 1,6% l&ecirc;n&nbsp;<abbr>1.687 tỷ đồng</abbr>. Sau khi thống nhất với Tổng cục Thuế - Bộ T&agrave;i ch&iacute;nh, c&ocirc;ng ty xổ số được giao nộp ng&acirc;n s&aacute;ch&nbsp;<abbr>3.750 tỷ đồng</abbr>. Tuy nhi&ecirc;n, Xổ số TP.HCM x&acirc;y dựng chỉ ti&ecirc;u phấn đấu nộp về&nbsp;<abbr>4.272 tỷ đồng</abbr>.</p>\n\n<p>C&ocirc;ng ty TNHH MTV Xổ số kiến thiết TP.HCM l&agrave; doanh nghiệp li&ecirc;n tục dẫn đầu doanh thu kinh doanh xổ số truyền thống cả nước.</p>\n\n<p>Một phần l&yacute; do l&agrave; theo quy định của Bộ T&agrave;i ch&iacute;nh, doanh nghiệp n&agrave;y được ph&eacute;p ph&aacute;t h&agrave;nh 2 ng&agrave;y/tuần l&agrave; thứ Hai v&agrave; thứ Bảy, trong khi c&aacute;c doanh nghiệp xổ số truyền thống khu vực miền Nam chỉ được ph&aacute;t h&agrave;nh một ng&agrave;y trong tuần.</p>\n\n<p>Ngo&agrave;i ra, tỷ lệ ti&ecirc;u thụ v&eacute; của Xổ số TP.HCM đạt tr&ecirc;n 97%. Năm nay, với 105 kỳ xổ, c&ocirc;ng ty n&agrave;y t&iacute;nh to&aacute;n mỗi kỳ b&aacute;n v&eacute; thu về&nbsp;<abbr>120 tỷ đồng</abbr>, ri&ecirc;ng 8 kỳ v&eacute; xu&acirc;n thu về&nbsp;<abbr>20 tỷ đồng</abbr>/kỳ.</p>\n\n<p>tỷ đồngXỔ SỐ TP.HCM Đ&Atilde; C&Oacute; 7 NĂM LI&Ecirc;N TIẾP L&Atilde;I TRƯỚC THUẾ TR&Ecirc;NNGH&Igrave;N TỶKQKD của Xổ số TP.HCM. Nguồn: BCTC DN.Doanh thuLợi nhuận trước thuếNăm 2017Năm 2018Năm 2019Năm 2020Năm 2021Năm 2022Năm 2023Kế hoạch 202405k10k15k</p>\n\n<p>Theo số liệu từ Bộ T&agrave;i ch&iacute;nh, tổng số thu từ hoạt động xổ số kiến thiết năm 2023 đ&atilde; vượt hơn&nbsp;<abbr>8.300 tỷ đồng</abbr>, tương ứng vượt 22% so với dự to&aacute;n Quốc hội ph&ecirc; duyệt.</p>\n\n<p>Tổng số thu từ hoạt động n&agrave;y năm 2023 đạt tới 45.880 tỷ đồng. Đ&acirc;y l&agrave; số thu lớn nhất từ hoạt động xổ số kiến thiết từ trước đến nay. Đ&oacute;ng g&oacute;p chủ yếu cho ng&acirc;n s&aacute;ch từ hoạt động xổ số kiến thiết l&agrave; 21 c&ocirc;ng ty xổ số ở ph&iacute;a Nam gồm TP.HCM, B&igrave;nh Dương, Đồng Nai...</p>\n\n<p>Doanh thu xổ số truyền thống chiếm gần 96%. Đ&aacute;ng ch&uacute; &yacute;, xổ số truyền thống tại khu vực miền Nam với 21 c&ocirc;ng ty đ&oacute;ng g&oacute;p hơn 93% thị trường xổ số cả nước.</p>\n',
          Image: '/images/content/DC10899/covpm5c5.png',
          Highlight: true,
          Position: 0,
          View: 0,
          DayNum: 10,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-03-27T10:56:22.55',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: 'F37B7DF2-181A-47B6-A34F-DB6A2738555A',
          Index: 306,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'FB873680-7553-4E36-84A7-9143DC578CC7',
          Language: 'vi',
          Alias: 'cong-trinh-phan-tich-lien-minh-sai-lam-my-ngo-dinh-diem',
          Title: 'Công trình phân tích liên minh sai lầm Mỹ - Ngô Đình Diệm',
          Intro:
            'Nhà nghiên cứu Edward Miller lý giải bản chất mối quan hệ giữa chính quyền Ngô Đình Diệm và Mỹ, khẳng định chính sách của liên minh này không được người dân ủng hộ.',
          Html: '<h3 style="text-align: center;"><span style="font-size:20px;"><em><strong>Học tiếng Việt để nghi&ecirc;n cứu</strong></em></span></h3>\n\n<p>&nbsp;</p>\n\n<p>Về việc đến với nghi&ecirc;n cứu chiến tranh Việt Nam (theo c&aacute;ch gọi của Mỹ về cuộc đấu tranh chống đế quốc Mỹ, thống nhất đất nước của nh&acirc;n d&acirc;n Việt Nam), t&aacute;c giả Edward Miller kể chuyện khi c&ograve;n l&agrave; sinh vi&ecirc;n cao học cần t&igrave;m đề t&agrave;i l&agrave;m luận văn. Trong suốt những năm th&aacute;ng trưởng th&agrave;nh, &ocirc;ng biết đến nhiều c&ocirc;ng tr&igrave;nh nghi&ecirc;n cứu về vấn đề chiến tranh ở Việt Nam, trong nhiều thập kỷ đ&acirc;y l&agrave; vấn đề được c&ocirc;ng ch&uacute;ng Mỹ đặc biệt quan t&acirc;m.</p>\n\n<p>Song Edward nhận thấy họ đa phần đều kh&ocirc;ng biết tiếng Việt, do đ&oacute; s&aacute;ch, phim của họ tập trung v&agrave;o quan điểm của người Mỹ, tổng thống Mỹ, ch&iacute;nh phủ Mỹ, thiếu khuyết g&oacute;c nh&igrave;n của người trong cuộc - nh&acirc;n d&acirc;n miền Nam. Điều n&agrave;y đ&atilde; th&ocirc;i th&uacute;c &ocirc;ng học tiếng Việt từ năm 1995 để tiếp cận đa dạng nguồn t&agrave;i liệu, đặc biệt l&agrave; c&aacute;c tư liệu tiếng Việt của Việt Nam Cộng h&ograve;a từ kho lưu trữ của c&aacute;c nước phương T&acirc;y.</p>\n\n<p>T&aacute;c phẩm&nbsp;<em>Li&ecirc;n minh sai lầm: Ng&ocirc; &ETH;&igrave;nh Diệm, Mỹ v&agrave; số phận Nam Việt Nam&nbsp;</em>ra đời v&agrave;o năm 2013, rất l&acirc;u sau khi Edward đ&atilde; ho&agrave;n th&agrave;nh chương tr&igrave;nh thạc sĩ, lấy bằng tiến sĩ v&agrave; tiếp tục giảng dạy, nghi&ecirc;n cứu chuy&ecirc;n s&acirc;u về chiến tranh ở Việt Nam v&agrave; vai tr&ograve; của cuộc chiến n&agrave;y trong lịch sử Mỹ đương đại. Cuốn s&aacute;ch được dịch v&agrave; lần đầu giới thiệu đến độc giả Việt Nam năm 2016.</p>\n\n<p><img alt="lien minh sai lam anh 1" src="https://photo.znews.vn/w860/Uploaded/zgsgtn/2024_03_25/misalliance_1__1.jpg" /></p>\n\n<p>Nh&acirc;n dịp t&aacute;i bản cuốn s&aacute;ch, t&aacute;c giả Edward Miller c&ugrave;ng nh&agrave; nghi&ecirc;n cứu, dịch giả, giảng vi&ecirc;n Trường Đại học Khoa học X&atilde; hội v&agrave; Nh&acirc;n văn, Đại học Quốc gia H&agrave; Nội L&ecirc; Nguy&ecirc;n Long đ&atilde; c&oacute; buổi giao lưu, tr&ograve; chuyện c&ugrave;ng độc giả tại Đường s&aacute;ch Nguyễn Văn B&igrave;nh (quận 1, TP.HCM) v&agrave;o chiều 25/3. Đ&ocirc;ng đảo độc giả, nh&agrave; nghi&ecirc;n cứu v&agrave; đặc biệt l&agrave; sinh vi&ecirc;n chuy&ecirc;n ng&agrave;nh lịch sử, quốc tế học... đ&atilde; tham dự sự kiện.</p>\n\n<p>Về kỷ niệm viết s&aacute;ch, Edward cho biết thử th&aacute;ch với &ocirc;ng l&agrave; việc học tiếng Việt. Vượt qua thử th&aacute;ch ng&ocirc;n ngữ, &ocirc;ng gặp thuận lợi l&acirc;u d&agrave;i về sau khi &ocirc;ng tiếp x&uacute;c v&agrave; tr&ograve; chuyện với nhiều người Mỹ gốc Việt hay những người nước ngo&agrave;i am hiểu về cuộc chiến v&agrave; giỏi tiếng Việt. Đến nay Edward vẫn đang tiếp tục miệt m&agrave;i học tiếng Việt. Trong buổi giao lưu &ocirc;ng chủ yếu tr&ograve; chuyện bằng tiếng Việt, trừ những đoạn kh&oacute; nhằn mới n&oacute;i tiếng Anh v&agrave; nhờ đến sự hỗ trợ của dịch giả v&agrave; MC.</p>\n\n<h3 style="text-align: center;"><span style="font-size:20px;"><em><strong>Nh&igrave;n lịch sử đa chiều</strong></em></span></h3>\n\n<p>&nbsp;</p>\n\n<p>Với tựa s&aacute;ch&nbsp;<em>Li&ecirc;n minh sai lầm</em>, đ&uacute;c kết của t&aacute;c giả l&agrave; người Mỹ n&ecirc;n học c&aacute;ch &quot;lắng nghe v&agrave; thừa nhận c&aacute;c quan điểm kh&aacute;c biệt để từ đ&oacute; c&oacute; tinh thần đối thoại&quot;.</p>\n\n<p>&Ocirc;ng cũng nhận định một lầm lạc của nhiều l&atilde;nh đạo trong chiến tranh l&agrave; họ nghĩ m&igrave;nh ở rất gần chiến thắng n&ecirc;n đưa ra hứa hẹn, song thực tế th&igrave; chiến thắng &quot;ở xa vời vợi&quot;. &Ocirc;ng cho rằng ch&iacute;nh s&aacute;ch của ch&iacute;nh quyền Mỹ v&agrave; Ng&ocirc; Đ&igrave;nh Diệm &quot;kh&ocirc;ng thuyết phục được người d&acirc;n miền Nam theo đuổi v&agrave; ủng hộ&quot;. Do đ&oacute; m&agrave; chiến tranh ng&agrave;y c&agrave;ng t&agrave;n khốc v&agrave; g&acirc;y ra nhiều chết ch&oacute;c hơn, &quot;l&agrave; một thảm họa cho cả Mỹ v&agrave; Việt Nam&quot; (a disaster for both America and Vietnam).</p>\n\n<p>S&aacute;ch Li&ecirc;n minh sai lầm: Ng&ocirc; &ETH;&igrave;nh Diệm, Mỹ v&agrave; số phận Nam Việt Nam t&aacute;i bản năm 2024 với phần phụ lục bổ sung. Ảnh: NXB Ch&iacute;nh trị Quốc gia Sự thật.</p>\n\n<table align="left" style="width: 100%;">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td><img alt="lien minh sai lam anh 2" height="1395" imgid="6759175" src="https://photo.znews.vn/w360/Uploaded/zgsgtn/2024_03_25/lien_minh_sai_lam2024_01_01.jpg" title="liên minh sai lầm ảnh 2" width="985" /></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<p>S&aacute;ch&nbsp;<em>Li&ecirc;n minh sai lầm: Ng&ocirc; &ETH;&igrave;nh Diệm, Mỹ v&agrave; số phận Nam Việt Nam</em>&nbsp;t&aacute;i bản năm 2024 với phần phụ lục bổ sung. Ảnh:&nbsp;<em>NXB Ch&iacute;nh trị Quốc gia Sự thật.</em></p>\n\t\t\t</td>\n\t\t</tr>\n\t</tbody>\n</table>\n\n<p style="text-align: center;">Trong lần t&aacute;i bản năm 2024 n&agrave;y, Nh&agrave; xuất bản Ch&iacute;nh trị quốc gia Sự thật bổ sung v&agrave;o nội dung s&aacute;ch một c&ocirc;ng tr&igrave;nh nghi&ecirc;n cứu của t&aacute;c giả về chấn hưng t&ocirc;n gi&aacute;o v&agrave; kh&iacute;a cạnh ch&iacute;nh trị của c&ocirc;ng cuộc kiến quốc - g&oacute;c nh&igrave;n kh&aacute;c về &ldquo;Biến cố Phật gi&aacute;o&rdquo; năm 1963 ở Nam Việt Nam.</p>\n\n<p>Nh&agrave; nghi&ecirc;n cứu Nguy&ecirc;n Long nhận định rằng t&aacute;c giả đ&atilde; đặt biến cố n&agrave;y cũng như nhiều sự kiện kh&aacute;c v&agrave;o bối cảnh rộng hơn, từ đ&oacute; cho thấy động cơ đằng sau quyết định của c&aacute;c nh&acirc;n vật kh&ocirc;ng hề mang t&iacute;nh &quot;tất định luận&quot;. Theo đ&oacute;, rất nhiều sai lầm đ&atilde; c&oacute; thể tr&aacute;nh khỏi nhưng do nhiều can thiệp ngẫu nhi&ecirc;n, do cả sự tự tin của Ng&ocirc; Đ&igrave;nh Nhu - Ng&ocirc; Đ&igrave;nh Diệm mới dẫn đến kết cục sau cuối.</p>\n\n<p>&Ocirc;ng Nguy&ecirc;n Long đ&aacute;nh gi&aacute; cuốn s&aacute;ch l&agrave; &quot;một trong những c&ocirc;ng tr&igrave;nh xuất sắc về lịch sử chiến tranh, đặt Việt Nam Cộng h&ograve;a trong bối cảnh rộng hơn để t&igrave;m ra nguy&ecirc;n nh&acirc;n h&igrave;nh th&agrave;nh v&agrave; sụp đổ của chế độ n&agrave;y&quot;. Theo &ocirc;ng, t&aacute;c phẩm c&ocirc;ng phu n&agrave;y đ&atilde; cung cấp một bức tranh to&agrave;n cảnh về một giai đoạn lịch sử đặc biệt.</p>\n\n<p>&Ocirc;ng nhận định cuốn s&aacute;ch c&ograve;n l&agrave; tham khảo quan trọng cho giới nghi&ecirc;n cứu ở phương ph&aacute;p nghi&ecirc;n cứu, c&aacute;ch lập luận, đặt vấn đề, c&aacute;ch sắp xếp v&agrave; x&acirc;u chuỗi để kể một c&acirc;u chuyện hay.</p>\n',
          Image: '/images/content/DC10899/xdghmhx2.png',
          Highlight: true,
          Position: 0,
          View: 0,
          DayNum: 10,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-03-27T10:54:44.723',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
        {
          Id: '949A93B9-3374-45FE-8743-E129CC4737EC',
          Index: 301,
          AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
          CategoryId: 'A15546E6-3361-47DE-833C-1B5F04599579',
          Language: 'vi',
          Alias: 'ronaldo-noi-nong',
          Title: 'Ronaldo nổi nóng',
          Intro:
            'Cristiano Ronaldo phản ứng với tổ trọng tài sau thất bại 0-2 của Bồ Đào Nha trước Slovenia ở trận giao hữu rạng sáng 27/3 (giờ Hà Nội)',
          Html: '<p><img src="https://photo.znews.vn/w960/Uploaded/bpivpawv/2024_03_25/Ronaldo1.jpeg" /></p>\n\n<p>Tr&ecirc;n đường tiến v&agrave;o đường hầm của s&acirc;n Stadion Stozice (Ljubljana, Slovenia), Ronaldo nổi cơn thịnh nộ. Si&ecirc;u sao người Bồ Đ&agrave;o Nha được cho l&agrave; chửi thề v&agrave; mắng mỏ tổ trọng t&agrave;i: &quot;Đồ qu&aacute;i quỷ, phải l&agrave; hai quả phạt đền nh&eacute;&quot;.</p>\n\n<p>Ph&uacute;t 80 của trận đấu, tuyển Bồ Đ&agrave;o Nha c&oacute; t&igrave;nh huống d&agrave;n xếp tấn c&ocirc;ng hay. Diogo Dalot chuyền b&oacute;ng ch&iacute;nh x&aacute;c cho Ronaldo tr&ecirc;n đ&agrave; lao l&ecirc;n trong v&ugrave;ng cấm địa Slovenia. Cầu thủ chủ nh&agrave; c&oacute; t&aacute;c động đẩy từ ph&iacute;a sau, khiến ng&ocirc;i sao của Al Nassr ng&atilde; nh&agrave;o xuống s&acirc;n.</p>\n\n<p>D&ugrave; vậy, trọng t&agrave;i ch&iacute;nh Irfan Peljto lại kh&ocirc;ng cho Bồ Đ&agrave;o Nha được hưởng quả phạt đền. Tr&ecirc;n mạng x&atilde; hội, người d&ugrave;ng cảm thấy rất bức x&uacute;c, cho rằng Ronaldo v&agrave; c&aacute;c đồng đội đ&atilde; bị &quot;đ&aacute;nh cắp&quot; một quả penalty.</p>\n\n<p>Trước Slovenia, Ronaldo chơi trọn vẹn 90 ph&uacute;t, tung ra 2 c&uacute; s&uacute;t, một trong số đ&oacute; tr&uacute;ng đ&iacute;ch. Si&ecirc;u sao 39 tuổi thực hiện th&agrave;nh c&ocirc;ng một pha r&ecirc; dắt qua người, đạt tỷ lệ chuyền b&oacute;ng ch&iacute;nh x&aacute;c 87%, c&oacute; 1 đường chuyền mở ra cơ hội.</p>\n\n<p>Trong hiệp một, ở pha d&agrave;n xếp tấn c&ocirc;ng trung lộ, Ronaldo thực hiện t&igrave;nh huống chuyền b&oacute;ng bằng ngực điệu nghệ cho Joao Cancelo. Pha b&oacute;ng n&agrave;y gi&uacute;p cựu sao Man Utd nhận được lời khen tr&ecirc;n mạng x&atilde; hội.</p>\n\n<p>Tuyển Bồ Đ&agrave;o Nha chơi kh&ocirc;ng tệ trước Slovenia. Tuy nhi&ecirc;n, đo&agrave;n qu&acirc;n của HLV Roberto Martinez lại kh&ocirc;ng thể chuyển h&oacute;a được c&aacute;c cơ hội th&agrave;nh b&agrave;n, để rồi trả gi&aacute;. Từ ph&uacute;t 72 đến 80, tuyển Slovenia li&ecirc;n tiếp ghi được c&aacute;c b&agrave;n thắng do c&ocirc;ng Adam Gnezda Cerin v&agrave; Timi Max El&scaron;nik.</p>\n\n<p>Với tuyển Bồ Đ&agrave;o Nha, trận thua 0-2 trước Slovenia mới l&agrave; thất bại đầu ti&ecirc;n của họ dưới thời HLV Roberto Martinez. Ronaldo v&agrave; c&aacute;c đồng đội sẽ c&oacute; th&ecirc;m 3 trận giao hữu v&agrave;o th&aacute;ng 6, gặp Phần lan, Croatia v&agrave; CH Ireland trước khi bước v&agrave;o VCK EURO 2024.</p>\n',
          Image: '/images/content/DC10899/a1jd0djy.png',
          Highlight: true,
          Position: 0,
          View: 0,
          DayNum: 7,
          Rate: 5,
          MetaTitle: null,
          MetaDescription: null,
          MetaKeyword: null,
          MetaTags: null,
          StartPoint: null,
          EndPoint: null,
          ShowSearchFrom: false,
          ShowPriceTable: false,
          CreatedDate: '2024-03-27T10:45:47.777',
          RelatedId: null,
          Visible: true,
          Category: null,
        },
      ],
      TotalItem: 5,
      TotalPage: 1,
      PageIndex: 1,
      PageSize: 10,
      HasPreviousPage: true,
      HasNextPage: false,
      OrderBy: 'CreatedDate',
      SortType: 'Desc',
      GetAll: false,
      Filter: [{ Name: 'Highlight', Value: 'true', Contain: false }],
      CustomProperties: null,
      Message: 'Thành công',
      StatusCode: '000',
      Success: true,
      Expired: false,
      Language: 'vi',
    },
  };
}
