/* eslint-disable @typescript-eslint/no-non-null-assertion */
/* eslint-disable @typescript-eslint/ban-ts-comment */
import { PREFIX_FLIGHT_TICKET_XLSX_NAME } from '@env';
import { Data } from '@services/axios';
import {
  AirlineRealm,
  AirportRealm,
  FlightTicketInList,
} from '@services/realm/models';
import { realmRef } from '@services/realm/provider';
import { images } from '@vna-base/assets/image';
import { flightTicketActions } from '@vna-base/redux/action-slice';
import { getAccount } from '@vna-base/redux/selector';
import { translate } from '@vna-base/translations/translate';
import {
  TicketStatus,
  TicketStatusDetails,
  delay,
  scale,
  validResponse,
} from '@vna-base/utils';
import { createFlightTicketInListFromAxios } from '@vna-base/utils/realm/flight-ticket';
import { takeLatestListeners } from '@vna-base/utils/redux/listener';
import dayjs from 'dayjs';
import cloneDeep from 'lodash.clonedeep';
import isEmpty from 'lodash.isempty';
import { Platform } from 'react-native';
import ReactNativeBlobUtil from 'react-native-blob-util';
import Share from 'react-native-share';
import { UpdateMode } from 'realm';
import XLSX from 'xlsx';

export const runFlightTicketListener = () => {
  takeLatestListeners()({
    actionCreator: flightTicketActions.getListFlightTicket,
    effect: async (action, listenerApi) => {
      const { filterForm, pageIndex } = action.payload;

      if (!pageIndex) {
        realmRef.current?.write(() => {
          realmRef.current?.delete(
            realmRef.current?.objects(FlightTicketInList.schema.name),
          );
        });

        listenerApi.dispatch(
          flightTicketActions.saveResultFilter({
            list: [],
            pageIndex: 1,
            totalPage: 1,
          }),
        );

        listenerApi.dispatch(flightTicketActions.changeIsLoadingFilter(true));
      }

      let _filterForm = filterForm;

      if (!isEmpty(_filterForm)) {
        listenerApi.dispatch(flightTicketActions.savedFilterForm(_filterForm));
      } else {
        _filterForm = listenerApi.getState().flightTicket.filterForm!;
      }

      // const response = await Data.ticketTicketGetListCreate({
      //   PageSize: PAGE_SIZE_ORDER,
      //   PageIndex: pageIndex,
      //   OrderBy: _filterForm.OrderBy,
      //   SortType: _filterForm.SortType ?? SortType.Desc,
      //   Filter: _filterForm.Filter,
      //   From: dayjs(_filterForm.Range.from).format(),
      //   To: dayjs(_filterForm.Range.to).format(),
      //   GetAll: _filterForm.GetAll,
      // });

      const response = {
        data: {
          List: [
            {
              Fee: 0,
              Total: 4679000,
              DepartDate: '2024-10-20T19:50:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: '738',
              TicketNumber: '7382300000047',
              BookingCode: '5DWHEE',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'SGN',
              MultiCity: false,
              OrgTotal: 4679000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: true,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 4679000,
              Id: '6F0A6AD0-21E1-4B24-885F-57BC01A65055',
              Index: 4378,
              SubAgId: null,
              NetPrice: 4679000,
              OrderId: '958581E3-A097-4809-8849-00BADB97D950',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 2,
              Sandbox: false,
              FareClass: 'N',
              GivenName: 'TUAN NGHIA',
              Vat: 0,
              Tax: 1401000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 1401000,
              OrgFare: 3278000,
              Segments: 'VNHANSGN-VNSGNHAN',
              StartPoint: 'HAN',
              Currency: 'VND',
              ServiceType: 'FLIGHT',
              ReturnDate: null,
              FareBasis: 'NPXVNF',
              Booking: null,
              Surname: 'TRAN',
              System: 'VN',
              Remark: 'PAX 738-2300000047/ETVN/17OCT24/SGNVN28BM/37980003',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9291',
              IssueDate: '2024-10-17T14:41:23.543',
              PassengerId: '0873AC07-65C1-49C9-9D59-64F2F1411A84',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: '861E5995-04D8-4E6D-A260-CCD5059C67D8',
              Fare: 3278000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'TRAN TUAN NGHIA',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 4679000,
              DepartDate: '2024-10-20T19:50:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: '738',
              TicketNumber: '7382300000046',
              BookingCode: '5DWHEE',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'SGN',
              MultiCity: false,
              OrgTotal: 4679000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: true,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 4679000,
              Id: '9B892FD4-3EC7-4A04-9FDE-6548C7530BFB',
              Index: 4377,
              SubAgId: null,
              NetPrice: 4679000,
              OrderId: '958581E3-A097-4809-8849-00BADB97D950',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 2,
              Sandbox: false,
              FareClass: 'N',
              GivenName: 'MINH THU',
              Vat: 0,
              Tax: 1401000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 1401000,
              OrgFare: 3278000,
              Segments: 'VNHANSGN-VNSGNHAN',
              StartPoint: 'HAN',
              Currency: 'VND',
              ServiceType: 'FLIGHT',
              ReturnDate: null,
              FareBasis: 'NPXVNF',
              Booking: null,
              Surname: 'NGUYEN',
              System: 'VN',
              Remark: 'PAX 738-2300000046/ETVN/17OCT24/SGNVN28BM/37980003',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9291',
              IssueDate: '2024-10-17T14:41:23.54',
              PassengerId: '94FABF30-19A7-4AD9-84E5-8B7EF3876F46',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: '861E5995-04D8-4E6D-A260-CCD5059C67D8',
              Fare: 3278000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'NGUYEN MINH THU',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 1929000,
              DepartDate: '2024-10-17T23:00:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: '738',
              TicketNumber: '7382300000043',
              BookingCode: '5DTX3L',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'SGN',
              MultiCity: false,
              OrgTotal: 1929000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: false,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 1929000,
              Id: '58673FEA-9EC8-4F20-9311-AFB973571488',
              Index: 4376,
              SubAgId: null,
              NetPrice: 1929000,
              OrderId: '76916FF9-5F6E-4FB8-8E81-873313D2DCB7',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 1,
              Sandbox: false,
              FareClass: 'T',
              GivenName: 'KIEN',
              Vat: 0,
              Tax: 670000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 670000,
              OrgFare: 1259000,
              Segments: 'VNHANSGN',
              StartPoint: 'HAN',
              Currency: 'VND',
              ServiceType: 'FLIGHT',
              ReturnDate: null,
              FareBasis: 'TPXVNF',
              Booking: null,
              Surname: 'TRAN',
              System: 'VN',
              Remark: 'PAX 738-2300000043/ETVN/17OCT24/SGNVN28BM/37980003',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9290',
              IssueDate: '2024-10-17T14:26:09.447',
              PassengerId: '1469D8A2-2536-47CA-8A2F-7B1266558F7A',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: '733262D1-C8EB-491E-ADA0-D377C15C5937',
              Fare: 1259000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'TRAN KIEN',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 1724000,
              DepartDate: '2024-10-23T22:00:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: '738',
              TicketNumber: '7382300000042',
              BookingCode: '5DTIEY',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'HAN',
              MultiCity: false,
              OrgTotal: 1724000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: false,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 1724000,
              Id: '39D38713-0C02-4797-B71A-77457D208F12',
              Index: 4375,
              SubAgId: null,
              NetPrice: 1724000,
              OrderId: 'D0265E0C-8B4D-4F61-AC01-F6EB30FCA4CF',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 1,
              Sandbox: false,
              FareClass: 'E',
              GivenName: 'HUU THO',
              Vat: 0,
              Tax: 655000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 655000,
              OrgFare: 1069000,
              Segments: 'VNSGNHAN',
              StartPoint: 'SGN',
              Currency: 'VND',
              ServiceType: 'FLIGHT',
              ReturnDate: null,
              FareBasis: 'EPXVNF',
              Booking: null,
              Surname: 'NGUYEN',
              System: 'VN',
              Remark: 'PAX 738-2300000042/ETVN/17OCT24/SGNVN28BM/37980003',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9289',
              IssueDate: '2024-10-17T14:22:58.03',
              PassengerId: '96784529-D833-4953-97F5-C33172F190F5',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: '5C9C73E8-0664-4128-B1EF-945978D04AB3',
              Fare: 1069000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'NGUYEN HUU THO',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 1724000,
              DepartDate: '2024-10-23T22:00:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: '738',
              TicketNumber: '7382300000041',
              BookingCode: '5DTIEY',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'HAN',
              MultiCity: false,
              OrgTotal: 1724000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: false,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 1724000,
              Id: '7F168E1A-88B0-4AB2-9595-E31545D78864',
              Index: 4374,
              SubAgId: null,
              NetPrice: 1724000,
              OrderId: 'D0265E0C-8B4D-4F61-AC01-F6EB30FCA4CF',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 1,
              Sandbox: false,
              FareClass: 'E',
              GivenName: 'VAN NAM',
              Vat: 0,
              Tax: 655000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 655000,
              OrgFare: 1069000,
              Segments: 'VNSGNHAN',
              StartPoint: 'SGN',
              Currency: 'VND',
              ServiceType: 'FLIGHT',
              ReturnDate: null,
              FareBasis: 'EPXVNF',
              Booking: null,
              Surname: 'HOANG',
              System: 'VN',
              Remark: 'PAX 738-2300000041/ETVN/17OCT24/SGNVN28BM/37980003',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9289',
              IssueDate: '2024-10-17T14:22:58.027',
              PassengerId: '51523A53-642F-468B-BB78-98107598C2CF',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: '5C9C73E8-0664-4128-B1EF-945978D04AB3',
              Fare: 1069000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'HOANG VAN NAM',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 1566000,
              DepartDate: '2024-10-20T06:10:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: null,
              TicketNumber: '7382412102155',
              BookingCode: 'FBTJNK',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'SGN',
              MultiCity: false,
              OrgTotal: 1566000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: false,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 1566000,
              Id: 'A79BB62E-781B-4F25-87A3-9BB4C8ECBC2C',
              Index: 4372,
              SubAgId: null,
              NetPrice: 1566000,
              OrderId: 'D0265E0C-8B4D-4F61-AC01-F6EB30FCA4CF',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 1,
              Sandbox: false,
              FareClass: 'T',
              GivenName: 'VAN NAM',
              Vat: 108000,
              Tax: 549000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 657000,
              OrgFare: 909000,
              Segments: 'QHHANSGN',
              StartPoint: 'HAN',
              Currency: 'VND',
              ServiceType: 'TE',
              ReturnDate: null,
              FareBasis: 'TES0F',
              Booking: null,
              Surname: 'HOANG',
              System: 'VN',
              Remark: 'Flight ticket issued by API',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9289',
              IssueDate: '2024-10-17T14:22:57.967',
              PassengerId: '2B594206-9FE2-4DFB-8BF1-9E2A7007A547',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: 'A4DCF578-9355-4AF4-AF7F-03388884D9BD',
              Fare: 909000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'HOANG VAN NAM',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 1566000,
              DepartDate: '2024-10-20T06:10:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: null,
              TicketNumber: '7382412102156',
              BookingCode: 'FBTJNK',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'SGN',
              MultiCity: false,
              OrgTotal: 1566000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: false,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 1566000,
              Id: 'A914B17B-E9C5-4B41-B585-F07702C43D0C',
              Index: 4373,
              SubAgId: null,
              NetPrice: 1566000,
              OrderId: 'D0265E0C-8B4D-4F61-AC01-F6EB30FCA4CF',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 1,
              Sandbox: false,
              FareClass: 'T',
              GivenName: 'HUU THO',
              Vat: 108000,
              Tax: 549000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 657000,
              OrgFare: 909000,
              Segments: 'QHHANSGN',
              StartPoint: 'HAN',
              Currency: 'VND',
              ServiceType: 'TE',
              ReturnDate: null,
              FareBasis: 'TES0F',
              Booking: null,
              Surname: 'NGUYEN',
              System: 'VN',
              Remark: 'Flight ticket issued by API',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9289',
              IssueDate: '2024-10-17T14:22:57.967',
              PassengerId: 'F7B7EE07-534C-4FDF-BD3A-EC2846FC3992',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: 'A4DCF578-9355-4AF4-AF7F-03388884D9BD',
              Fare: 909000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'NGUYEN HUU THO',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 3206000,
              DepartDate: '2024-10-23T13:05:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: '738',
              TicketNumber: '7382300000040',
              BookingCode: '5DT5WK',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'HAN',
              MultiCity: false,
              OrgTotal: 3206000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: false,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'inbound',
              SubAgCode: null,
              TotalPrice: 3206000,
              Id: '5F3B5D4E-2202-414D-808C-56655C0CF6D2',
              Index: 4371,
              SubAgId: null,
              NetPrice: 3206000,
              OrderId: '912BA33C-4AF0-408A-8922-907E68C18958',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 1,
              Sandbox: false,
              FareClass: 'E',
              GivenName: 'THI HONG',
              Vat: 0,
              Tax: 2249000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 2249000,
              OrgFare: 957000,
              Segments: 'VNSINHAN',
              StartPoint: 'SIN',
              Currency: 'VND',
              ServiceType: 'FLIGHT',
              ReturnDate: null,
              FareBasis: 'EOXAS',
              Booking: null,
              Surname: 'NGUYEN',
              System: 'VN',
              Remark:
                'PAX 738-2300000040/ETVN/VND3206000/17OCT24/SGNVN28BM/37980003',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9288',
              IssueDate: '2024-10-17T14:20:03.22',
              PassengerId: 'C8829F4E-9A81-4842-A1EF-C6DC9CFDD265',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: '39E87BBE-5510-4175-93BC-CE324D2F6870',
              Fare: 957000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'NGUYEN THI HONG',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 3206000,
              DepartDate: '2024-10-23T13:05:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: '738',
              TicketNumber: '7382300000039',
              BookingCode: '5DT5WK',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'HAN',
              MultiCity: false,
              OrgTotal: 3206000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: false,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'inbound',
              SubAgCode: null,
              TotalPrice: 3206000,
              Id: '6FDC2FCA-6847-4C7B-8EEB-34FC819F82C7',
              Index: 4370,
              SubAgId: null,
              NetPrice: 3206000,
              OrderId: '912BA33C-4AF0-408A-8922-907E68C18958',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 1,
              Sandbox: false,
              FareClass: 'E',
              GivenName: 'MINH HOANG',
              Vat: 0,
              Tax: 2249000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 2249000,
              OrgFare: 957000,
              Segments: 'VNSINHAN',
              StartPoint: 'SIN',
              Currency: 'VND',
              ServiceType: 'FLIGHT',
              ReturnDate: null,
              FareBasis: 'EOXAS',
              Booking: null,
              Surname: 'NGO',
              System: 'VN',
              Remark:
                'PAX 738-2300000039/ETVN/VND3206000/17OCT24/SGNVN28BM/37980003',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9288',
              IssueDate: '2024-10-17T14:20:03.22',
              PassengerId: '45F8B3DD-2ABD-4342-90BF-3A2B984CD03F',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: '39E87BBE-5510-4175-93BC-CE324D2F6870',
              Fare: 957000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'NGO MINH HOANG',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 3188000,
              DepartDate: '2024-10-20T14:30:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: '738',
              TicketNumber: '7382300000038',
              BookingCode: '5DSVFM',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'SGN',
              MultiCity: false,
              OrgTotal: 3188000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: true,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 3188000,
              Id: '31DD4F55-A198-4849-B544-D10D04E2182C',
              Index: 4369,
              SubAgId: null,
              NetPrice: 3188000,
              OrderId: 'D538F960-0AB7-45AA-B673-DA604A02888E',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 2,
              Sandbox: false,
              FareClass: 'R,A',
              GivenName: 'VAN HUNG',
              Vat: 0,
              Tax: 1290000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 1290000,
              OrgFare: 1898000,
              Segments: 'VNHANSGN-VNSGNHAN',
              StartPoint: 'HAN',
              Currency: 'VND',
              ServiceType: 'FLIGHT',
              ReturnDate: null,
              FareBasis: 'RPXVNF,AAP2VNF',
              Booking: null,
              Surname: 'NGO',
              System: 'VN',
              Remark: 'PAX 738-2300000038/ETVN/17OCT24/SGNVN28BM/37980003',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9287',
              IssueDate: '2024-10-17T14:12:56.687',
              PassengerId: '644C3AFE-9D57-4817-83DD-685137591CC8',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: 'FB79B8B1-1CF7-4A9D-AC7C-83B2402FBF7E',
              Fare: 1898000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'NGO VAN HUNG',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 3188000,
              DepartDate: '2024-10-20T14:30:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: '738',
              TicketNumber: '7382300000037',
              BookingCode: '5DSVFM',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'SGN',
              MultiCity: false,
              OrgTotal: 3188000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: true,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 3188000,
              Id: '7E9D42F2-05A6-42FF-A59C-BBB633A3D188',
              Index: 4368,
              SubAgId: null,
              NetPrice: 3188000,
              OrderId: 'D538F960-0AB7-45AA-B673-DA604A02888E',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 2,
              Sandbox: false,
              FareClass: 'R,A',
              GivenName: 'MINH HAI',
              Vat: 0,
              Tax: 1290000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 1290000,
              OrgFare: 1898000,
              Segments: 'VNHANSGN-VNSGNHAN',
              StartPoint: 'HAN',
              Currency: 'VND',
              ServiceType: 'FLIGHT',
              ReturnDate: null,
              FareBasis: 'RPXVNF,AAP2VNF',
              Booking: null,
              Surname: 'NGO',
              System: 'VN',
              Remark: 'PAX 738-2300000037/ETVN/17OCT24/SGNVN28BM/37980003',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9287',
              IssueDate: '2024-10-17T14:12:56.683',
              PassengerId: '3432A86E-5BCD-4990-A898-F10186BEDA0B',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: 'FB79B8B1-1CF7-4A9D-AC7C-83B2402FBF7E',
              Fare: 1898000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'NGO MINH HAI',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 2728000,
              DepartDate: '2024-10-20T06:00:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: '738',
              TicketNumber: '7382300000033',
              BookingCode: '5DR2AN',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'SGN',
              MultiCity: false,
              OrgTotal: 2728000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: false,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 2728000,
              Id: '35E7CB0A-5FA3-4121-B01A-85470C416A42',
              Index: 4367,
              SubAgId: null,
              NetPrice: 2728000,
              OrderId: '35559B14-B013-4500-9C5E-6E02BB889E3C',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 1,
              Sandbox: false,
              FareClass: 'L',
              GivenName: 'MINH TUAN',
              Vat: 0,
              Tax: 729000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 729000,
              OrgFare: 1999000,
              Segments: 'VNHANSGN',
              StartPoint: 'HAN',
              Currency: 'VND',
              ServiceType: 'FLIGHT',
              ReturnDate: null,
              FareBasis: 'LPXVNF',
              Booking: null,
              Surname: 'NGO',
              System: 'VN',
              Remark: 'PAX 738-2300000033/ETVN/17OCT24/SGNVN28BM/37980003',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9286',
              IssueDate: '2024-10-17T14:06:26.617',
              PassengerId: 'A1A78885-AD14-4FA2-B57A-37F00DFEB6F0',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: '22078ACB-3E84-450B-AC34-D8EB67256CF8',
              Fare: 1999000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'NGO MINH TUAN',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 1933000,
              DepartDate: '2024-10-20T17:40:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: null,
              TicketNumber: '7382412102149',
              BookingCode: 'FBPY7G',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'SGN',
              MultiCity: false,
              OrgTotal: 1933000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: false,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 1933000,
              Id: '1497917F-2E18-4FA1-873D-20687EE071E2',
              Index: 4366,
              SubAgId: null,
              NetPrice: 1933000,
              OrderId: 'EC52BE8F-2B8D-46C2-8714-69EA1986BA18',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 1,
              Sandbox: false,
              FareClass: 'N',
              GivenName: 'QUANG QUAN',
              Vat: 135000,
              Tax: 549000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 684000,
              OrgFare: 1249000,
              Segments: 'QHHANSGN',
              StartPoint: 'HAN',
              Currency: 'VND',
              ServiceType: 'TE',
              ReturnDate: null,
              FareBasis: 'NES0F',
              Booking: null,
              Surname: 'NGO',
              System: 'VN',
              Remark: 'Flight ticket issued by API',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9285',
              IssueDate: '2024-10-17T14:02:08.973',
              PassengerId: 'D2EDFC42-5248-48DC-8BF0-6C66C64418EE',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: '276C7B8D-CC11-41D1-A843-F505BC0B5BD5',
              Fare: 1249000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'NGO QUANG QUAN',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 2340000,
              DepartDate: '2024-10-20T19:50:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: '738',
              TicketNumber: '7382300000032',
              BookingCode: '5DQ75D',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'SGN',
              MultiCity: false,
              OrgTotal: 2340000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: false,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 2340000,
              Id: '0B7256D5-8484-48D0-BB77-C5A226AEA351',
              Index: 4365,
              SubAgId: null,
              NetPrice: 2340000,
              OrderId: '99A366B9-7967-42E1-A9F7-C4F6695E745F',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 1,
              Sandbox: false,
              FareClass: 'N',
              GivenName: 'QUYEN',
              Vat: 0,
              Tax: 701000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 701000,
              OrgFare: 1639000,
              Segments: 'VNHANSGN',
              StartPoint: 'HAN',
              Currency: 'VND',
              ServiceType: 'FLIGHT',
              ReturnDate: null,
              FareBasis: 'NPXVNF',
              Booking: null,
              Surname: 'NGO',
              System: 'VN',
              Remark: 'PAX 738-2300000032/ETVN/17OCT24/SGNVN28BM/37980003',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9284',
              IssueDate: '2024-10-17T13:58:45.18',
              PassengerId: '0BEE4279-BC40-4E36-94C9-3C2A7F082B9E',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: '3DB07489-07E7-49CC-85F5-122E5A6936DC',
              Fare: 1639000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'NGO QUYEN',
              AgentName: null,
            },
            {
              Fee: 0,
              Total: 1739000,
              DepartDate: '2024-10-17T19:50:00',
              Charges: [],
              SubAgName: null,
              ConjTktNum: null,
              TicketNumber: '7382412102145',
              BookingCode: 'FB2EEM',
              TicketRelated: null,
              IssueUser: '669635EA-7688-4A8F-B995-2B2A375C9DA3',
              Order: null,
              TicketType: 'OPEN',
              EndPoint: 'SGN',
              MultiCity: false,
              OrgTotal: 1739000,
              TicketStatus: 'OPEN',
              AgentCode: null,
              Roundtrip: false,
              OfficeId: '21301132-DE26-436B-8BC8-F4B02CF14BEA',
              CreatedUser: 'Vu Trung Thong',
              FlightType: 'domestic',
              SubAgCode: null,
              TotalPrice: 1739000,
              Id: 'CF2A6880-FCB3-4ADB-AEF6-A3F126F6342B',
              Index: 4364,
              SubAgId: null,
              NetPrice: 1739000,
              OrderId: '4ACC2659-BAAE-40B1-A0F3-98CB543CF140',
              OrgCurrency: 'VND',
              ServiceCode: null,
              Itinerary: 1,
              Sandbox: false,
              FareClass: 'Q',
              GivenName: 'KIEN',
              Vat: 121000,
              Tax: 549000,
              Passenger: null,
              Profit: 0,
              RelatedType: null,
              Source: 'API',
              Airline: 'VN',
              Visible: true,
              OrgTaxes: 670000,
              OrgFare: 1069000,
              Segments: 'QHHANSGN',
              StartPoint: 'HAN',
              Currency: 'VND',
              ServiceType: 'TE',
              ReturnDate: null,
              FareBasis: 'QES0F',
              Booking: null,
              Surname: 'TRAN',
              System: 'VN',
              Remark: 'Flight ticket issued by API',
              Tourcode: null,
              ListParent: null,
              OrderCode: '9278',
              IssueDate: '2024-10-17T10:55:27.007',
              PassengerId: '9747770A-61D3-497D-8367-5BB86E5ED5B3',
              AgentId: 'D4275221-ABEB-40AF-8526-98F1C52B362E',
              PaxType: 'ADT',
              BookingId: '387E3A00-4485-4E4D-9F19-3C6600A0DC99',
              Fare: 1069000,
              CreatedAvar: images.nvzudhoh,
              FullName: 'TRAN KIEN',
              AgentName: null,
            },
          ],
          SortType: 'Desc',
          StatusCode: '000',
          Message: null,
          HasPreviousPage: true,
          Expired: false,
          OrderBy: 'IssueDate',
          TotalPage: 2,
          PageIndex: 1,
          GetAll: false,
          Filter: [],
          TotalItem: 17,
          Success: true,
          Language: 'vi',
          PageSize: 15,
          HasNextPage: false,
          CustomProperties: null,
        },
      };

      if (validResponse(response)) {
        const { List: newFlightTickets, TotalPage } = response.data;
        const listId: Array<string | null> = cloneDeep(
          listenerApi.getState().flightTicket.resultFilter.list,
        );

        realmRef.current?.write(() => {
          newFlightTickets?.forEach(flTicket => {
            if (
              !realmRef.current?.objectForPrimaryKey<FlightTicketInList>(
                FlightTicketInList.schema.name,
                flTicket.Id!,
              )
            ) {
              // Không bị trùng thì lưu vào realm và push vào listOrderId
              createFlightTicketInListFromAxios(flTicket);

              listId.push(flTicket.Id!);
            } else {
              // bị trùng thì update data trong realm và xoá id trong listId, push vào cuối listId
              createFlightTicketInListFromAxios(flTicket, UpdateMode.Modified);

              const i = listId.findIndex(id => id === flTicket.Id);
              listId[i] = null;

              listId.push(flTicket.Id!);
            }
          });
        });

        listenerApi.dispatch(
          flightTicketActions.saveResultFilter({
            list: listId.filter(id => id !== null) as Array<string>,
            pageIndex: pageIndex ?? 1,
            totalPage: TotalPage ?? 1,
          }),
        );
      }

      if (!pageIndex) {
        listenerApi.dispatch(flightTicketActions.changeIsLoadingFilter(false));
      }
    },
  });

  takeLatestListeners(true, {
    showConfig: {
      lottie: 'loading',
      t18nSubtitle: 'common:please_wait_a_several_minute',
      t18nTitle: 'order:exporting_file',
      lottieStyle: { width: scale(182), height: scale(72) },
    },
    successConfig: {
      lottie: 'done',
      lottieStyle: { width: scale(182), height: scale(72) },
      t18nSubtitle: 'common:success',
      t18nTitle: 'order:saved_to_download_folder_success',
    },
    failedConfig: {
      lottie: 'failed',
      lottieStyle: { width: scale(182), height: scale(72) },
      t18nSubtitle: 'common:please_try_again',
      t18nTitle: 'common:failed',
    },
  })({
    actionCreator: flightTicketActions.exportExcel,
    effect: async (action, listenerApi) => {
      const from = action.payload;

      const { language } = listenerApi.getState().app;

      const form = {
        PageSize: 10_000,
        PageIndex: 1,
        OrderBy: from.OrderBy,
        SortType: from.SortType,
        From: dayjs(from.Range.from).format(),
        To: dayjs(from.Range.to).format(),
        GetAll: true,
      };
      const response = await Data.ticketTicketGetListCreate(form);

      if (validResponse(response)) {
        // xử lý excel

        const processedData =
          response.data.List?.map((flightTicket, index) => {
            return {
              Index: index, //Số thứ tự
              System: flightTicket.System, //Hệ thống
              Airline: realmRef.current?.objectForPrimaryKey<AirlineRealm>(
                AirlineRealm.schema.name,
                flightTicket.Airline as string,
              )?.[language === 'en' ? 'NameEn' : 'NameVi'], // Hãng
              TicketNumber: flightTicket.TicketNumber, // Số vé
              TicketStatus: flightTicket.TicketStatus
                ? translate(
                    TicketStatusDetails[
                      flightTicket.TicketStatus as TicketStatus
                    ].t18n,
                  )
                : null, // trajng thasi vé
              BookingCode: flightTicket.BookingCode, //Mã booking
              IssueDate: dayjs(flightTicket.IssueDate).format('DD/MM/YYYY'), // Ngày xuất
              IssueUser: getAccount(flightTicket.IssueUser)?.FullName, // Người xuất
              Passenger: flightTicket.FullName, // Họ tên khách
              PassengerType: flightTicket.PaxType, // Loại khách
              Amount: flightTicket.Total, // Số tiền xuất
              Currency: flightTicket.Currency, // Đơn vị tiền tệ
              StartPoint:
                flightTicket.StartPoint +
                ' - ' +
                realmRef.current?.objectForPrimaryKey<AirportRealm>(
                  AirportRealm.schema.name,
                  flightTicket.StartPoint as string,
                )?.City[language === 'en' ? 'NameEn' : 'NameVi'], // Điểm khởi hành
              EndPoint:
                flightTicket.EndPoint +
                ' - ' +
                realmRef.current?.objectForPrimaryKey<AirportRealm>(
                  AirportRealm.schema.name,
                  flightTicket.EndPoint as string,
                )?.City[language === 'en' ? 'NameEn' : 'NameVi'], // Điểm đến
              FareBasic: flightTicket.FareBasis, // FareBasic
              Remark: flightTicket.Remark, // Ghi chú
            };
          }) ?? [];

        processedData.unshift({
          //@ts-ignore
          Index: translate('flight_ticket:index'), //Số thứ tự
          System: translate('flight_ticket:system'), //Hệ thống
          Airline: translate('flight_ticket:airline'), // Hãng
          TicketNumber: translate('flight_ticket:ticket_number'), // Số vé
          TicketStatus: translate('flight_ticket:ticket_status'), // trạng thái vé
          BookingCode: translate('flight_ticket:booking_code'), //Mã booking
          IssueDate: translate('flight_ticket:issue_date'), // Ngày xuất
          IssueUser: translate('flight_ticket:issue_user'), // Người xuất
          Passenger: translate('flight_ticket:passenger'), // Họ tên khách
          PassengerType: translate('flight_ticket:passenger_type'), // Loại khách
          //@ts-ignore
          Amount: translate('flight_ticket:amount'), // Số tiền xuất
          Currency: translate('flight_ticket:currency'), // Đơn vị tiền tệ
          StartPoint: translate('flight_ticket:start_point'), // Điểm khởi hành
          EndPoint: translate('flight_ticket:end_point'), // Điểm đến
          FareBasic: translate('flight_ticket:fare_basic'), // FareBasic
          Remark: translate('flight_ticket:remark'), // Ghi chú
        });

        // Tạo sheet từ dữ liệu JSON
        const wb = XLSX.utils.book_new();

        const ws = XLSX.utils.json_to_sheet(processedData, {
          skipHeader: true,
        });

        // Định dạng độ rộng cho các cột cụ thể
        const columnWidths = [
          { wch: 4 }, //Số thứ tự
          { wch: 8 }, //Hệ thống
          { wch: 20 }, // Hãng
          { wch: 14 }, // Số vé
          { wch: 20 }, // trajng thasi ve
          { wch: 14 }, //Mã booking
          { wch: 20 }, // Ngày xuất
          { wch: 36 }, // Người xuất
          { wch: 36 }, // Họ tên khách
          { wch: 20 }, // Loại khách
          { wch: 14 }, // Số tiền xuất
          { wch: 6 }, // Đơn vị tiền tệ
          { wch: 36 }, // Điểm khởi hành
          { wch: 40 }, // Điểm đến
          { wch: 40 }, // FareBasic
          { wch: 40 }, // Ghi chú
        ];

        // Áp dụng độ rộng cho từng cột trong sheet
        ws['!cols'] = columnWidths;

        const AmountColumnIndex = 10; // Xác định chỉ số cột TotalPrice

        const AmountColumnChar = XLSX.utils.encode_col(AmountColumnIndex); // Chuyển đổi chỉ số sang ký tự cột

        const format = '#,##0_);\\(#,##0\\)'; // Định dạng số tiền (ví dụ: 1,000)

        for (let R = 1; R <= (response.data.List?.length ?? 0) + 1; ++R) {
          // Bắt đầu từ hàng thứ hai (hàng tiêu đề là hàng đầu tiên)

          //Amount
          const totalPriceCellRef = `${AmountColumnChar}${R}`;
          if (ws[totalPriceCellRef]) {
            ws[totalPriceCellRef].z = format; // Áp dụng định dạng cho từng ô trong cột TotalPrice
          }
        }

        XLSX.utils.book_append_sheet(wb, ws, 'FlightTicket');
        const wbout = XLSX.write(wb, { type: 'base64' });

        const fileName = `${PREFIX_FLIGHT_TICKET_XLSX_NAME}${dayjs().format(
          'YYYYMMDD_HHmmss',
        )}`;

        const filePath =
          ReactNativeBlobUtil.fs.dirs[
            Platform.OS === 'ios' ? 'DocumentDir' : 'LegacyDownloadDir'
          ] + `/${fileName}.xlsx`;

        await ReactNativeBlobUtil.fs.writeFile(filePath, wbout, 'base64');

        await delay(500);

        if (Platform.OS === 'ios') {
          await Share.open({
            url: filePath,
            saveToFiles: true,
            filename: fileName,
          });
          // ReactNativeBlobUtil.ios.presentOptionsMenu(filePath);
        } else {
          // showToast({
          //   type: 'success',
          //   t18n: 'order:saved_to_download_folder_success',
          // });
          // await ReactNativeBlobUtil.MediaCollection.copyToMediaStore(
          //   {
          //     name: fileName, // name of the file
          //     parentFolder: '', // subdirectory in the Media Store, e.g. HawkIntech/Files to create a folder HawkIntech with a subfolder Files and save the image within this folder
          //     mimeType:
          //       'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', // MIME type of the file
          //   },
          //   'Download', // Media Collection to store the file in ("Audio" | "Image" | "Video" | "Download")
          //   filePath, // Path to the file being copied in the apps own storage
          // );
          // await Share.open({
          //   type: 'file',
          //   url: filePath,
          // });
        }
      }
    },
  });
};
