import { SLICE_NAME } from '@redux/action-slice/constant';

export const GET_LIST_ACTIVITY_BY_AGENT =
  SLICE_NAME.ACTIVITY + 'GET_LIST_ACTIVITY_BY_AGENT';

export const GET_LIST_ACTIVITY = SLICE_NAME.ACTIVITY + 'GET_LIST_ACTIVITY';

export const INSERT_NEW_ACTIVITY = SLICE_NAME.ACTIVITY + 'INSERT_NEW_ACTIVITY';

export const DELETE_ACTIVITY = SLICE_NAME.ACTIVITY + 'DELETE_ACTIVITY';
