import { SLICE_NAME } from '@redux/action-slice/constant';

export const GET_LIST_AGENT = SLICE_NAME.AGENT + 'GET_LIST_AGENT';

export const LOAD_MORE_AGENT = SLICE_NAME.AGENT + 'LOAD_MORE_AGENT';

export const GET_ALL_AGENT = SLICE_NAME.AGENT + 'GET_ALL_AGENT';

export const GET_LIST_AGENT_TYPE = SLICE_NAME.AGENT + 'GET_LIST_AGENT_TYPE';

export const GET_ALL_AGENT_TYPE = SLICE_NAME.AGENT + 'GET_ALL_AGENT_TYPE';

export const GET_ALL_AGENT_GROUP = SLICE_NAME.AGENT + 'GET_ALL_AGENT_GROUP';

export const GET_AGENT_DETAIL_BY_ID =
  SLICE_NAME.AGENT + 'GET_AGENT_DETAIL_BY_ID';

export const INSERT_NEW_AGENT = SLICE_NAME.AGENT + 'INSERT_NEW_AGENT';

export const DELETE_AGENT = SLICE_NAME.AGENT + 'DELETE_AGENT';

export const UPDATE_AGENT_DETAIL = SLICE_NAME.AGENT + 'UPDATE_AGENT_DETAIL';

export const RESTORE_AGENT = SLICE_NAME.AGENT + 'RESTORE_AGENT';

export const UPDATE_BALANCE = SLICE_NAME.AGENT + 'UPDATE_BALANCE';
