import { SLICE_NAME } from '@redux/action-slice/constant';

export const GET_LIST_BOOKING = SLICE_NAME.BOOKING + 'GET_LIST_BOOKING';

export const EXPORT_EXCEL_BOOKING = SLICE_NAME.BOOKING + 'EXPORT_EXCEL_BOOKING';

export const GET_BOOKING_DETAIL_BY_ID_BOOKING_CODE =
  SLICE_NAME.BOOKING + 'GET_BOOKING_DETAIL_BY_ID_BOOKING_CODE';

export const UPDATE_BOOKING = SLICE_NAME.BOOKING + 'UPDATE_BOOKING';

export const DELETE_BOOKING = SLICE_NAME.BOOKING + 'DELETE_BOOKING';

export const GET_BOOKING_VERSION_DETAIL =
  SLICE_NAME.BOOKING + 'GET_BOOKING_VERSION_DETAIL';
