import { SLICE_NAME } from '@redux/action-slice/constant';

export const GET_FLIGHT_ACTIONS_BY_BOOKING_ID =
  SLICE_NAME.BOOKING_ACTION + 'GET_FLIGHT_ACTIONS_BY_BOOKING_ID';

export const ISSUE_TICKET = SLICE_NAME.BOOKING_ACTION + 'ISSUE_TICKET';

export const VOID_TICKET = SLICE_NAME.BOOKING_ACTION + 'VOID_TICKET';

export const ISSUE_EMD = SLICE_NAME.BOOKING_ACTION + 'ISSUE_EMD';

export const RE_BOOK = SLICE_NAME.BOOKING_ACTION + 'RE_BOOK';

export const CANCEL_BOOKING = SLICE_NAME.BOOKING_ACTION + 'CANCEL_BOOKING';

export const SEND_EMAILS = SLICE_NAME.BOOKING_ACTION + 'SEND_EMAILS';

export const SPLIT_PASSENGER = SLICE_NAME.BOOKING_ACTION + 'SPLIT_PASSENGER';

export const PASSPORT_UPDATE = SLICE_NAME.BOOKING_ACTION + 'PASSPORT_UPDATE';

export const MEMBER_SHIP_UPDATE =
  SLICE_NAME.BOOKING_ACTION + 'MEMBER_SHIP_UPDATE';

export const GET_SEAT_MAP_ACTION_BOOKING =
  SLICE_NAME.BOOKING_ACTION + 'GET_SEAT_MAP_ACTION_BOOKING';

export const GET_ANCILLARIES_ACTION_BOOKING =
  SLICE_NAME.BOOKING_ACTION + 'GET_ANCILLARIES_ACTION_BOOKING';

export const UPDATE_SEAT_MAP = SLICE_NAME.BOOKING_ACTION + 'UPDATE_SEAT_MAP';

export const UPDATE_ANCILLARIES =
  SLICE_NAME.BOOKING_ACTION + 'UPDATE_ANCILLARIES';

export const CHANGE_FLIGHT = SLICE_NAME.BOOKING_ACTION + 'CHANGE_FLIGHT';

export const UPDATE_PASSENGER = SLICE_NAME.BOOKING_ACTION + 'UPDATE_PASSENGER';

export const REFUND_TICKET = SLICE_NAME.BOOKING_ACTION + 'REFUND_TICKET';

export const UPDATE_CONTACT = SLICE_NAME.BOOKING_ACTION + 'UPDATE_CONTACT';

export const EXCHANGE_TICKET = SLICE_NAME.BOOKING_ACTION + 'EXCHANGE_TICKET';

export const BOOKING_PRICING = SLICE_NAME.BOOKING_ACTION + 'BOOKING_PRICING';
