import { SLICE_NAME } from '@redux/action-slice/constant';

export const GET_CHARGE_BY_ORDER_ID =
  SLICE_NAME.CHARGE + 'GET_CHARGE_BY_ORDER_ID';

export const FLIGHT_CHARGE_UPDATE = SLICE_NAME.CHARGE + 'FLIGHT_CHARGE_UPDATE';

export const FLIGHT_CHARGE_DELETE = SLICE_NAME.CHARGE + 'FLIGHT_CHARGE_DELETE';

export const FLIGHT_CHARGE_INSERT = SLICE_NAME.CHARGE + 'FLIGHT_CHARGE_INSERT';
