import { SLICE_NAME } from '@vna-base/redux/action-slice/constant';

export const GET_CONFIG_TICKET = SLICE_NAME.CONFIG_TICKET + 'GET_CONFIG_TICKET';

export const UPDATE_CONFIG_TICKET =
  SLICE_NAME.CONFIG_TICKET + 'UPDATE_CONFIG_TICKET';

export const GET_TICKET_TEMPLATES =
  SLICE_NAME.CONFIG_TICKET + 'GET_TICKET_TEMPLATES';

export const GET_LANGUAGES_TICKET =
  SLICE_NAME.CONFIG_TICKET + 'GET_LANGUAGES_TICKET';
