import { SLICE_NAME } from '@vna-base/redux/action-slice/constant';

export const GET_CONFIG_EMAIL = SLICE_NAME.CONFIG_EMAIL + 'GET_CONFIG_EMAIL';

export const GET_LANGUAGES_EMAIL =
  SLICE_NAME.CONFIG_EMAIL + 'GET_LANGUAGES_EMAIL';

export const GET_EMAIL_TEMPLATES =
  SLICE_NAME.CONFIG_EMAIL + 'GET_EMAIL_TEMPLATES';

export const UPDATE_CONFIG_EMAIL =
  SLICE_NAME.CONFIG_EMAIL + 'UPDATE_CONFIG_EMAIL';
