import { SLICE_NAME } from '@redux/action-slice/constant';

export const GET_LIST_CONTACT_BY_AGENT_ID =
  SLICE_NAME.CONTACT + 'GET_LIST_CONTACT_BY_AGENT_ID';

export const GET_CONTACT = SLICE_NAME.CONTACT + 'GET_CONTACT';

export const INSERT_CONTACT = SLICE_NAME.CONTACT + 'INSERT_CONTACT';

export const DELETE_CONTACT = SLICE_NAME.CONTACT + 'DELETE_CONTACT';
