import { SLICE_NAME } from '@vna-base/redux/action-slice/constant';

export const GET_CURRENT_ACCOUNT =
  SLICE_NAME.CURRENT_ACCOUNT + 'GET_CURRENT_ACCOUNT';

export const LOAD_ACCOUNT_DATA =
  SLICE_NAME.CURRENT_ACCOUNT + 'LOAD_ACCOUNT_DATA';

export const RESET_PASSWORD = SLICE_NAME.CURRENT_ACCOUNT + 'RESET_PASSWORD';
