import { SLICE_NAME } from '@vna-base/redux/action-slice/constant';

export const GET_LIST_SPECIALIZE_NEWS =
  SLICE_NAME.DBS_CONTENT + 'GET_LIST_SPECIALIZE_NEWS';

export const GET_LIST_OUTSTANDING_POLICY =
  SLICE_NAME.DBS_CONTENT + 'GET_LIST_OUTSTANDING_POLICY';

export const GET_DETAIL_DBS_CONTENT =
  SLICE_NAME.DBS_CONTENT + 'GET_DETAIL_DBS_CONTENT';
