import { SLICE_NAME } from '@vna-base/redux/action-slice/constant';

export const GET_LIST_EMPLOYEE_BY_AGENT =
  SLICE_NAME.EMPLOYEE + 'GET_LIST_EMPLOYEE_BY_AGENT';

export const GET_ALL_EMPLOYEE_OF_CURRENT_ACCOUNT =
  SLICE_NAME.EMPLOYEE + 'GET_ALL_EMPLOYEE_OF_CURRENT_ACCOUNT';
