import { SLICE_NAME } from '@redux/action-slice/constant';

export const GET_LIST_FLIGHT_TICKET =
  SLICE_NAME.FLIGHT_TICKET + 'GET_LIST_FLIGHT_TICKET';

export const EXPORT_EXCEL_FLIGHT_TICKET =
  SLICE_NAME.FLIGHT_TICKET + 'EXPORT_EXCEL_FLIGHT_TICKET';
