import { SLICE_NAME } from '@redux/action-slice/constant';

export const SEARCH_FLIGHTS = SLICE_NAME.FLIGHT_SEARCH + 'SEARCH_FLIGHTS';

export const SEARCH_FLIGHTS_BY_MONTH =
  SLICE_NAME.FLIGHT_SEARCH + 'SEARCH_FLIGHTS_BY_MONTH';
