import { SLICE_NAME } from '@vna-base/redux/action-slice/constant';

export const GET_LIST_ORDER = SLICE_NAME.ORDER + 'GET_LIST_ORDER';

export const EXPORT_EXCEL_ORDERS = SLICE_NAME.ORDER + 'EXPORT_EXCEL';

export const GET_ORDER_DETAIL = SLICE_NAME.ORDER + 'GET_ORDER_DETAIL';

export const DELETE_ORDER = SLICE_NAME.ORDER + 'DELETE_ORDER';

export const GET_LIST_REMARK = SLICE_NAME.ORDER + 'GET_LIST_REMARK';

export const GET_ACTIVITY = SLICE_NAME.ORDER + 'GET_ACTIVITY';

export const INSERT_REMARK = SLICE_NAME.ORDER + 'INSERT_REMARK';

export const UPDATE_ORDER_DETAIL = SLICE_NAME.ORDER + 'UPDATE_ORDER_DETAIL';
