import { SLICE_NAME } from '@redux/action-slice/constant';

export const GET_LIST_PAYMENT_EXPENSE =
  SLICE_NAME.PAYMENT + 'GET_LIST_PAYMENT_EXPENSE';
export const GET_LIST_PAYMENT_RECEIVE =
  SLICE_NAME.PAYMENT + 'GET_LIST_PAYMENT_RECEIVE';

export const GET_LIST_PAYMENT_HISTORY =
  SLICE_NAME.PAYMENT + 'GET_LIST_PAYMENT_HISTORY';

export const EXPORT_EXCEL_PAYMENT_HISTORY = SLICE_NAME.PAYMENT + 'EXPORT_EXCEL';
