import { SLICE_NAME } from '@vna-base/redux/action-slice/constant';

export const GET_LIST_POLICY = SLICE_NAME.POLICY + 'GET_LIST_POLICY';

export const POLICY_DETAIL = SLICE_NAME.POLICY + 'POLICY_DETAIL';

export const DELETE_POLICY = SLICE_NAME.POLICY + 'DELETE_POLICY';

export const UPDATE_POLICY = SLICE_NAME.POLICY + 'UPDATE_POLICY';

export const CREATE_POLICY = SLICE_NAME.POLICY + 'CREATE_POLICY';

export const RESTORE_POLICY = SLICE_NAME.POLICY + 'RESTORE_POLICY';
