import { SLICE_NAME } from '@redux/action-slice/constant';

export const GET_LIST_TOPUP_HISTORY =
  SLICE_NAME.TOPUP + 'GET_LIST_TOPUP_HISTORY';

export const GET_ALL_TYPE = SLICE_NAME.TOPUP + 'GET_ALL_TYPE';

export const GET_TOPUP_DETAIL_BY_ID_AND_PARENT_ID =
  SLICE_NAME.TOPUP + 'GET_TOPUP_DETAIL_BY_ID_AND_PARENT_ID';

export const EXPORT_EXCEL_TOP_UP_HISTORY = SLICE_NAME.TOPUP + 'EXPORT_EXCEL';
