import { SLICE_NAME } from '@redux/action-slice/constant';

export const GET_USER_ACCOUNT = SLICE_NAME.USER_ACCOUNT + 'GET_USER_ACCOUNT';

export const UPDATE_USER_ACCOUNT =
  SLICE_NAME.USER_ACCOUNT + 'UPDATE_USER_ACCOUNT';

export const GET_LIST_USER_ACCOUNT =
  SLICE_NAME.USER_ACCOUNT + 'GET_LIST_USER_ACCOUNT';

export const LOAD_MORE_USER_ACCOUNT =
  SLICE_NAME.USER_ACCOUNT + 'LOAD_MORE_USER_ACCOUNT';

export const ADD_NEW_USER_ACCOUNT =
  SLICE_NAME.USER_ACCOUNT + 'ADD_NEW_USER_ACCOUNT';

export const DELETE_USER_ACCOUNT =
  SLICE_NAME.USER_ACCOUNT + 'DELETE_USER_ACCOUNT';

export const RESET_PASS_USER_ACCOUNT =
  SLICE_NAME.USER_ACCOUNT + 'RESET_PASS_USER_ACCOUNT';

export const RESTORE_USER_ACCOUNT =
  SLICE_NAME.USER_ACCOUNT + 'RESTORE_USER_ACCOUNT';
