import { SLICE_NAME } from '@vna-base/redux/action-slice/constant';

export const GET_LIST_USER_SUB_AGET =
  SLICE_NAME.USER_SUB_AGENT + 'GET_LIST_USER_SUB_AGET';

export const GET_USER_SUB_AGT = SLICE_NAME.USER_SUB_AGENT + 'GET_USER_SUB_AGT';

export const INSERT_NEW_USER_SUB_AGT =
  SLICE_NAME.USER_SUB_AGENT + 'INSERT_NEW_USER_SUB_AGT';

export const UPDATE_USER_SUB_AGT =
  SLICE_NAME.USER_SUB_AGENT + 'UPDATE_USER_SUB_AGT';

export const RESET_PASS_USER_SUB_AGT =
  SLICE_NAME.USER_SUB_AGENT + 'RESET_PASS_USER_SUB_AGT';

export const DELETE_USER_SUB_AGT =
  SLICE_NAME.USER_SUB_AGENT + 'DELETE_USER_SUB_AGT';

export const RESTORE_USER_SUB_AGT =
  SLICE_NAME.USER_SUB_AGENT + 'RESTORE_USER_SUB_AGT';
